
export const routeTemplates = {
    mainPage: "/",
    customerSignUp: "/customers/sign-up",
    customerLogIn: "/customers/log-in",
    customerSignUpOrLogIn: "/customers/sign-up-or-log-in",
    customerLandingPage: "/customers/landing-page",
    enterpriseStaffSignUpOrLogIn: "/enterprise-staff/sign-up-or-log-in",
    entrepreneurSignUp: "/entrepreneurs/sign-up",
    entrepreneurLogIn: "/entrepreneurs/log-in",
    entrepreneurLandingPage: "/entrepreneur-landing-page",
    createEnterprise: "/create-enterprise",
    enterprisePublic: "/enterprises/:enterpriseId/public",
    enterpriseStaff: "/enterprises/:enterpriseId/staff",
    createEnterpriseEmployee: "/enterprises/:enterpriseId/create-employee",
    logInEnterpriseEmployee: "/employee/log-in",
    enterpriseCreateService: "/enterprises/:enterpriseId/create-service",
    serviceSearch: "/services/search",
    servicePublicPage: "/services/:serviceId",
    createServiceReview: "/services/:serviceId/create-review",
    adminReportsPage: "/admins/landing-page",
    adminLogIn: "/admins/log-in",
    manageServicePage: "/services/:serviceId/manage",
    regularAdminListPage: "/head-admin/regular-admins",
    editRegularAdminPage: "/edit-regular-admin/:userId",
    createRegularAdminPage: "/create-regular-admin"
};