FROM openjdk:23-slim
RUN apt-get update && apt-get install -y maven curl
WORKDIR /app/backend
COPY backend/pom.xml .
COPY openapi.yaml ..
RUN [ "mvn", "dependency:go-offline", "-B" ]
COPY backend .
CMD [ "mvn", "spring-boot:run" ]