/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SendAdyenSessionResultRequest,
  SendAdyenSessionResultResponse,
} from '../models/index';
import {
    SendAdyenSessionResultRequestFromJSON,
    SendAdyenSessionResultRequestToJSON,
    SendAdyenSessionResultResponseFromJSON,
    SendAdyenSessionResultResponseToJSON,
} from '../models/index';

export interface SendAdyenSessionResultOperationRequest {
    sendAdyenSessionResultRequest: SendAdyenSessionResultRequest;
}

/**
 * 
 */
export class AdyenApi extends runtime.BaseAPI {

    /**
     */
    async sendAdyenSessionResultRaw(requestParameters: SendAdyenSessionResultOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendAdyenSessionResultResponse>> {
        if (requestParameters['sendAdyenSessionResultRequest'] == null) {
            throw new runtime.RequiredError(
                'sendAdyenSessionResultRequest',
                'Required parameter "sendAdyenSessionResultRequest" was null or undefined when calling sendAdyenSessionResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/adyen/adyen-session-result`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendAdyenSessionResultRequestToJSON(requestParameters['sendAdyenSessionResultRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendAdyenSessionResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async sendAdyenSessionResult(sendAdyenSessionResultRequest: SendAdyenSessionResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendAdyenSessionResultResponse> {
        const response = await this.sendAdyenSessionResultRaw({ sendAdyenSessionResultRequest: sendAdyenSessionResultRequest }, initOverrides);
        return await response.value();
    }

}
