/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomAppointmentRequest,
  CreateNonCustomAppointmentRequest,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject4,
} from '../models/index';
import {
    CreateCustomAppointmentRequestFromJSON,
    CreateCustomAppointmentRequestToJSON,
    CreateNonCustomAppointmentRequestFromJSON,
    CreateNonCustomAppointmentRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
} from '../models/index';

export interface CreateCustomAppointmentOperationRequest {
    serviceId: number;
    createCustomAppointmentRequest: CreateCustomAppointmentRequest;
}

export interface CreateNonCustomAppointmentOperationRequest {
    serviceId: number;
    createNonCustomAppointmentRequest: CreateNonCustomAppointmentRequest;
}

/**
 * 
 */
export class AppointmentsApi extends runtime.BaseAPI {

    /**
     */
    async createCustomAppointmentRaw(requestParameters: CreateCustomAppointmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling createCustomAppointment().'
            );
        }

        if (requestParameters['createCustomAppointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomAppointmentRequest',
                'Required parameter "createCustomAppointmentRequest" was null or undefined when calling createCustomAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/custom-appointments/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomAppointmentRequestToJSON(requestParameters['createCustomAppointmentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createCustomAppointment(serviceId: number, createCustomAppointmentRequest: CreateCustomAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomAppointmentRaw({ serviceId: serviceId, createCustomAppointmentRequest: createCustomAppointmentRequest }, initOverrides);
    }

    /**
     */
    async createNonCustomAppointmentRaw(requestParameters: CreateNonCustomAppointmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling createNonCustomAppointment().'
            );
        }

        if (requestParameters['createNonCustomAppointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createNonCustomAppointmentRequest',
                'Required parameter "createNonCustomAppointmentRequest" was null or undefined when calling createNonCustomAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/non-custom-appointments/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNonCustomAppointmentRequestToJSON(requestParameters['createNonCustomAppointmentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createNonCustomAppointment(serviceId: number, createNonCustomAppointmentRequest: CreateNonCustomAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createNonCustomAppointmentRaw({ serviceId: serviceId, createNonCustomAppointmentRequest: createNonCustomAppointmentRequest }, initOverrides);
    }

}
