/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomAppointmentRequest,
  CreateNonCustomAppointmentRequest,
  GetCustomerLandingPagePendingAppointmentResponseItem,
  GetCustomerLandingPageRejectedAppointmentResponseItem,
  GetCustomerLandingPageScheduledAppointmentResponseItem,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject4,
  RejectPendingAppointmentRequest,
} from '../models/index';
import {
    CreateCustomAppointmentRequestFromJSON,
    CreateCustomAppointmentRequestToJSON,
    CreateNonCustomAppointmentRequestFromJSON,
    CreateNonCustomAppointmentRequestToJSON,
    GetCustomerLandingPagePendingAppointmentResponseItemFromJSON,
    GetCustomerLandingPagePendingAppointmentResponseItemToJSON,
    GetCustomerLandingPageRejectedAppointmentResponseItemFromJSON,
    GetCustomerLandingPageRejectedAppointmentResponseItemToJSON,
    GetCustomerLandingPageScheduledAppointmentResponseItemFromJSON,
    GetCustomerLandingPageScheduledAppointmentResponseItemToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
    RejectPendingAppointmentRequestFromJSON,
    RejectPendingAppointmentRequestToJSON,
} from '../models/index';

export interface AcceptPendingAppointmentRequest {
    appointmentId: number;
}

export interface CancelAppointmentRequest {
    appointmentId: number;
}

export interface CreateCustomAppointmentOperationRequest {
    serviceId: number;
    createCustomAppointmentRequest: CreateCustomAppointmentRequest;
}

export interface CreateNonCustomAppointmentOperationRequest {
    serviceId: number;
    createNonCustomAppointmentRequest: CreateNonCustomAppointmentRequest;
}

export interface RejectPendingAppointmentOperationRequest {
    appointmentId: number;
    rejectPendingAppointmentRequest: RejectPendingAppointmentRequest;
}

/**
 * 
 */
export class AppointmentsApi extends runtime.BaseAPI {

    /**
     */
    async acceptPendingAppointmentRaw(requestParameters: AcceptPendingAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling acceptPendingAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/{appointmentId}/accept`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async acceptPendingAppointment(appointmentId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.acceptPendingAppointmentRaw({ appointmentId: appointmentId }, initOverrides);
    }

    /**
     */
    async cancelAppointmentRaw(requestParameters: CancelAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling cancelAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/{appointmentId}/cancel`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancelAppointment(appointmentId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelAppointmentRaw({ appointmentId: appointmentId }, initOverrides);
    }

    /**
     */
    async createCustomAppointmentRaw(requestParameters: CreateCustomAppointmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling createCustomAppointment().'
            );
        }

        if (requestParameters['createCustomAppointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomAppointmentRequest',
                'Required parameter "createCustomAppointmentRequest" was null or undefined when calling createCustomAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/custom-appointments/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomAppointmentRequestToJSON(requestParameters['createCustomAppointmentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createCustomAppointment(serviceId: number, createCustomAppointmentRequest: CreateCustomAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomAppointmentRaw({ serviceId: serviceId, createCustomAppointmentRequest: createCustomAppointmentRequest }, initOverrides);
    }

    /**
     */
    async createNonCustomAppointmentRaw(requestParameters: CreateNonCustomAppointmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling createNonCustomAppointment().'
            );
        }

        if (requestParameters['createNonCustomAppointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createNonCustomAppointmentRequest',
                'Required parameter "createNonCustomAppointmentRequest" was null or undefined when calling createNonCustomAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/non-custom-appointments/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNonCustomAppointmentRequestToJSON(requestParameters['createNonCustomAppointmentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createNonCustomAppointment(serviceId: number, createNonCustomAppointmentRequest: CreateNonCustomAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createNonCustomAppointmentRaw({ serviceId: serviceId, createNonCustomAppointmentRequest: createNonCustomAppointmentRequest }, initOverrides);
    }

    /**
     */
    async getMyFutureScheduledAppointmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetCustomerLandingPageScheduledAppointmentResponseItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/my-future-scheduled-appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCustomerLandingPageScheduledAppointmentResponseItemFromJSON));
    }

    /**
     */
    async getMyFutureScheduledAppointments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetCustomerLandingPageScheduledAppointmentResponseItem>> {
        const response = await this.getMyFutureScheduledAppointmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyPastScheduledAppointmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetCustomerLandingPageScheduledAppointmentResponseItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/my-past-appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCustomerLandingPageScheduledAppointmentResponseItemFromJSON));
    }

    /**
     */
    async getMyPastScheduledAppointments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetCustomerLandingPageScheduledAppointmentResponseItem>> {
        const response = await this.getMyPastScheduledAppointmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyPendingAppointmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetCustomerLandingPagePendingAppointmentResponseItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/my-pending-appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCustomerLandingPagePendingAppointmentResponseItemFromJSON));
    }

    /**
     */
    async getMyPendingAppointments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetCustomerLandingPagePendingAppointmentResponseItem>> {
        const response = await this.getMyPendingAppointmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyRejectedAppointmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetCustomerLandingPageRejectedAppointmentResponseItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/my-rejected-appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCustomerLandingPageRejectedAppointmentResponseItemFromJSON));
    }

    /**
     */
    async getMyRejectedAppointments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetCustomerLandingPageRejectedAppointmentResponseItem>> {
        const response = await this.getMyRejectedAppointmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async rejectPendingAppointmentRaw(requestParameters: RejectPendingAppointmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling rejectPendingAppointment().'
            );
        }

        if (requestParameters['rejectPendingAppointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'rejectPendingAppointmentRequest',
                'Required parameter "rejectPendingAppointmentRequest" was null or undefined when calling rejectPendingAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/appointments/{appointmentId}/reject`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RejectPendingAppointmentRequestToJSON(requestParameters['rejectPendingAppointmentRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async rejectPendingAppointment(appointmentId: number, rejectPendingAppointmentRequest: RejectPendingAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rejectPendingAppointmentRaw({ appointmentId: appointmentId, rejectPendingAppointmentRequest: rejectPendingAppointmentRequest }, initOverrides);
    }

}
