/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateIndependentEndUserRequest,
  InlineObject1,
  InlineObject3,
  InlineObject4,
} from '../models/index';
import {
    CreateIndependentEndUserRequestFromJSON,
    CreateIndependentEndUserRequestToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject3FromJSON,
    InlineObject3ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
} from '../models/index';

export interface CreateCustomerRequest {
    createIndependentEndUserRequest: CreateIndependentEndUserRequest;
}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI {

    /**
     * Create a customer
     */
    async createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createIndependentEndUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createIndependentEndUserRequest',
                'Required parameter "createIndependentEndUserRequest" was null or undefined when calling createCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIndependentEndUserRequestToJSON(requestParameters['createIndependentEndUserRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a customer
     */
    async createCustomer(createIndependentEndUserRequest: CreateIndependentEndUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomerRaw({ createIndependentEndUserRequest: createIndependentEndUserRequest }, initOverrides);
    }

}
