/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdyenWebhookRequest,
} from '../models/index';
import {
    AdyenWebhookRequestFromJSON,
    AdyenWebhookRequestToJSON,
} from '../models/index';

export interface SendAdyenPaymentStatusRequest {
    adyenWebhookRequest: AdyenWebhookRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async sendAdyenPaymentStatusRaw(requestParameters: SendAdyenPaymentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['adyenWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'adyenWebhookRequest',
                'Required parameter "adyenWebhookRequest" was null or undefined when calling sendAdyenPaymentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhooks/adyen`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdyenWebhookRequestToJSON(requestParameters['adyenWebhookRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async sendAdyenPaymentStatus(adyenWebhookRequest: AdyenWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendAdyenPaymentStatusRaw({ adyenWebhookRequest: adyenWebhookRequest }, initOverrides);
    }

}
