/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEnterprise,
  InlineObject,
} from '../models/index';
import {
    CreateEnterpriseFromJSON,
    CreateEnterpriseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

export interface CreateEnterpriseRequest {
    createEnterprise: CreateEnterprise;
}

/**
 * 
 */
export class EnterprisesApi extends runtime.BaseAPI {

    /**
     */
    async createEnterpriseRaw(requestParameters: CreateEnterpriseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createEnterprise'] == null) {
            throw new runtime.RequiredError(
                'createEnterprise',
                'Required parameter "createEnterprise" was null or undefined when calling createEnterprise().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JwtBearerAuth authentication
        }


        let urlPath = `/entreprises`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEnterpriseToJSON(requestParameters['createEnterprise']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createEnterprise(createEnterprise: CreateEnterprise, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createEnterpriseRaw({ createEnterprise: createEnterprise }, initOverrides);
    }

}
