/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomAppointmentsEnterpriseServiceRequest,
  CreateNoCustomAppointmentsEnterpriseServiceRequest,
  GetServiceCustomAppointmentsStatus200Response,
  GetServiceFreeCustomAppointmentsResponseItem,
  GetServiceFreeNonCustomAppointmentsResponseItem,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject4,
  ServiceSearchResponseItem,
} from '../models/index';
import {
    CreateCustomAppointmentsEnterpriseServiceRequestFromJSON,
    CreateCustomAppointmentsEnterpriseServiceRequestToJSON,
    CreateNoCustomAppointmentsEnterpriseServiceRequestFromJSON,
    CreateNoCustomAppointmentsEnterpriseServiceRequestToJSON,
    GetServiceCustomAppointmentsStatus200ResponseFromJSON,
    GetServiceCustomAppointmentsStatus200ResponseToJSON,
    GetServiceFreeCustomAppointmentsResponseItemFromJSON,
    GetServiceFreeCustomAppointmentsResponseItemToJSON,
    GetServiceFreeNonCustomAppointmentsResponseItemFromJSON,
    GetServiceFreeNonCustomAppointmentsResponseItemToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
    ServiceSearchResponseItemFromJSON,
    ServiceSearchResponseItemToJSON,
} from '../models/index';

export interface CreateCustomAppointmentsEnterpriseServiceOperationRequest {
    enterpriseId: number;
    createCustomAppointmentsEnterpriseServiceRequest: CreateCustomAppointmentsEnterpriseServiceRequest;
}

export interface CreateNoCustomAppointmentsEnterpriseServiceOperationRequest {
    enterpriseId: number;
    createNoCustomAppointmentsEnterpriseServiceRequest: CreateNoCustomAppointmentsEnterpriseServiceRequest;
}

export interface GetFreeNonCustomAppointmentsRequest {
    serviceId: number;
    dateInServiceTimezone: Date;
}

export interface GetFreeTimeWindowsForCustomAppointmentsRequest {
    serviceId: number;
    dateInServiceTimezone: Date;
}

export interface GetServiceCustomAppointmentsStatusRequest {
    serviceId: number;
}

export interface SearchServicesRequest {
    preferredLongitude: number;
    preferredLatitude: number;
    cathegory: string;
    maxDistanceKm: number;
    serviceName?: string;
    enterpriseName?: string;
    startDatetimeGlobal?: Date;
    endDatetimeGlobal?: Date;
}

/**
 * 
 */
export class EnterpriseServicesApi extends runtime.BaseAPI {

    /**
     */
    async createCustomAppointmentsEnterpriseServiceRaw(requestParameters: CreateCustomAppointmentsEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['enterpriseId'] == null) {
            throw new runtime.RequiredError(
                'enterpriseId',
                'Required parameter "enterpriseId" was null or undefined when calling createCustomAppointmentsEnterpriseService().'
            );
        }

        if (requestParameters['createCustomAppointmentsEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomAppointmentsEnterpriseServiceRequest',
                'Required parameter "createCustomAppointmentsEnterpriseServiceRequest" was null or undefined when calling createCustomAppointmentsEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/enterprises/{enterpriseId}/custom_appointment_services`;
        urlPath = urlPath.replace(`{${"enterpriseId"}}`, encodeURIComponent(String(requestParameters['enterpriseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomAppointmentsEnterpriseServiceRequestToJSON(requestParameters['createCustomAppointmentsEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createCustomAppointmentsEnterpriseService(enterpriseId: number, createCustomAppointmentsEnterpriseServiceRequest: CreateCustomAppointmentsEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomAppointmentsEnterpriseServiceRaw({ enterpriseId: enterpriseId, createCustomAppointmentsEnterpriseServiceRequest: createCustomAppointmentsEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async createNoCustomAppointmentsEnterpriseServiceRaw(requestParameters: CreateNoCustomAppointmentsEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['enterpriseId'] == null) {
            throw new runtime.RequiredError(
                'enterpriseId',
                'Required parameter "enterpriseId" was null or undefined when calling createNoCustomAppointmentsEnterpriseService().'
            );
        }

        if (requestParameters['createNoCustomAppointmentsEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createNoCustomAppointmentsEnterpriseServiceRequest',
                'Required parameter "createNoCustomAppointmentsEnterpriseServiceRequest" was null or undefined when calling createNoCustomAppointmentsEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/enterprises/{enterpriseId}/no_custom_appointment_services`;
        urlPath = urlPath.replace(`{${"enterpriseId"}}`, encodeURIComponent(String(requestParameters['enterpriseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNoCustomAppointmentsEnterpriseServiceRequestToJSON(requestParameters['createNoCustomAppointmentsEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createNoCustomAppointmentsEnterpriseService(enterpriseId: number, createNoCustomAppointmentsEnterpriseServiceRequest: CreateNoCustomAppointmentsEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createNoCustomAppointmentsEnterpriseServiceRaw({ enterpriseId: enterpriseId, createNoCustomAppointmentsEnterpriseServiceRequest: createNoCustomAppointmentsEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async getFreeNonCustomAppointmentsRaw(requestParameters: GetFreeNonCustomAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetServiceFreeNonCustomAppointmentsResponseItem>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getFreeNonCustomAppointments().'
            );
        }

        if (requestParameters['dateInServiceTimezone'] == null) {
            throw new runtime.RequiredError(
                'dateInServiceTimezone',
                'Required parameter "dateInServiceTimezone" was null or undefined when calling getFreeNonCustomAppointments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateInServiceTimezone'] != null) {
            queryParameters['dateInServiceTimezone'] = (requestParameters['dateInServiceTimezone'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/free-non-custom-appointment-slots/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetServiceFreeNonCustomAppointmentsResponseItemFromJSON));
    }

    /**
     */
    async getFreeNonCustomAppointments(serviceId: number, dateInServiceTimezone: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetServiceFreeNonCustomAppointmentsResponseItem>> {
        const response = await this.getFreeNonCustomAppointmentsRaw({ serviceId: serviceId, dateInServiceTimezone: dateInServiceTimezone }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFreeTimeWindowsForCustomAppointmentsRaw(requestParameters: GetFreeTimeWindowsForCustomAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetServiceFreeCustomAppointmentsResponseItem>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getFreeTimeWindowsForCustomAppointments().'
            );
        }

        if (requestParameters['dateInServiceTimezone'] == null) {
            throw new runtime.RequiredError(
                'dateInServiceTimezone',
                'Required parameter "dateInServiceTimezone" was null or undefined when calling getFreeTimeWindowsForCustomAppointments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateInServiceTimezone'] != null) {
            queryParameters['dateInServiceTimezone'] = (requestParameters['dateInServiceTimezone'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/free-time-windows-for-custom-appointments`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetServiceFreeCustomAppointmentsResponseItemFromJSON));
    }

    /**
     */
    async getFreeTimeWindowsForCustomAppointments(serviceId: number, dateInServiceTimezone: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetServiceFreeCustomAppointmentsResponseItem>> {
        const response = await this.getFreeTimeWindowsForCustomAppointmentsRaw({ serviceId: serviceId, dateInServiceTimezone: dateInServiceTimezone }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceCustomAppointmentsStatusRaw(requestParameters: GetServiceCustomAppointmentsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetServiceCustomAppointmentsStatus200Response>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getServiceCustomAppointmentsStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/custom-appointments-or-not`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetServiceCustomAppointmentsStatus200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceCustomAppointmentsStatus(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetServiceCustomAppointmentsStatus200Response> {
        const response = await this.getServiceCustomAppointmentsStatusRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchServicesRaw(requestParameters: SearchServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceSearchResponseItem>>> {
        if (requestParameters['preferredLongitude'] == null) {
            throw new runtime.RequiredError(
                'preferredLongitude',
                'Required parameter "preferredLongitude" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['preferredLatitude'] == null) {
            throw new runtime.RequiredError(
                'preferredLatitude',
                'Required parameter "preferredLatitude" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['cathegory'] == null) {
            throw new runtime.RequiredError(
                'cathegory',
                'Required parameter "cathegory" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['maxDistanceKm'] == null) {
            throw new runtime.RequiredError(
                'maxDistanceKm',
                'Required parameter "maxDistanceKm" was null or undefined when calling searchServices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['serviceName'] != null) {
            queryParameters['serviceName'] = requestParameters['serviceName'];
        }

        if (requestParameters['enterpriseName'] != null) {
            queryParameters['enterpriseName'] = requestParameters['enterpriseName'];
        }

        if (requestParameters['startDatetimeGlobal'] != null) {
            queryParameters['startDatetimeGlobal'] = (requestParameters['startDatetimeGlobal'] as any).toISOString();
        }

        if (requestParameters['endDatetimeGlobal'] != null) {
            queryParameters['endDatetimeGlobal'] = (requestParameters['endDatetimeGlobal'] as any).toISOString();
        }

        if (requestParameters['preferredLongitude'] != null) {
            queryParameters['preferredLongitude'] = requestParameters['preferredLongitude'];
        }

        if (requestParameters['preferredLatitude'] != null) {
            queryParameters['preferredLatitude'] = requestParameters['preferredLatitude'];
        }

        if (requestParameters['cathegory'] != null) {
            queryParameters['cathegory'] = requestParameters['cathegory'];
        }

        if (requestParameters['maxDistanceKm'] != null) {
            queryParameters['maxDistanceKm'] = requestParameters['maxDistanceKm'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceSearchResponseItemFromJSON));
    }

    /**
     */
    async searchServices(preferredLongitude: number, preferredLatitude: number, cathegory: string, maxDistanceKm: number, serviceName?: string, enterpriseName?: string, startDatetimeGlobal?: Date, endDatetimeGlobal?: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceSearchResponseItem>> {
        const response = await this.searchServicesRaw({ preferredLongitude: preferredLongitude, preferredLatitude: preferredLatitude, cathegory: cathegory, maxDistanceKm: maxDistanceKm, serviceName: serviceName, enterpriseName: enterpriseName, startDatetimeGlobal: startDatetimeGlobal, endDatetimeGlobal: endDatetimeGlobal }, initOverrides);
        return await response.value();
    }

}
