/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomAppointmentsEnterpriseServiceRequest,
  CreateEnterpriseServiceReviewRequest,
  CreateNoCustomAppointmentsEnterpriseServiceRequest,
  GetEnterpriseService200Response,
  GetEnterpriseServiceCustomServiceResponse,
  GetEnterpriseServiceNonCustomServiceResponse,
  GetEnterpriseServicePendingAppointmentResponse,
  GetEnterpriseServiceReviewResponse,
  GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponse,
  GetServiceCustomAppointmentsStatus200Response,
  GetServiceFreeCustomAppointmentsResponseItem,
  GetServiceFreeNonCustomAppointmentsResponseItem,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject4,
  InlineObject6,
  PatchCustomEnterpriseServiceRequest,
  PatchNonCustomEnterpriseServiceRequest,
  ServiceSearchResponseItem,
} from '../models/index';
import {
    CreateCustomAppointmentsEnterpriseServiceRequestFromJSON,
    CreateCustomAppointmentsEnterpriseServiceRequestToJSON,
    CreateEnterpriseServiceReviewRequestFromJSON,
    CreateEnterpriseServiceReviewRequestToJSON,
    CreateNoCustomAppointmentsEnterpriseServiceRequestFromJSON,
    CreateNoCustomAppointmentsEnterpriseServiceRequestToJSON,
    GetEnterpriseService200ResponseFromJSON,
    GetEnterpriseService200ResponseToJSON,
    GetEnterpriseServiceCustomServiceResponseFromJSON,
    GetEnterpriseServiceCustomServiceResponseToJSON,
    GetEnterpriseServiceNonCustomServiceResponseFromJSON,
    GetEnterpriseServiceNonCustomServiceResponseToJSON,
    GetEnterpriseServicePendingAppointmentResponseFromJSON,
    GetEnterpriseServicePendingAppointmentResponseToJSON,
    GetEnterpriseServiceReviewResponseFromJSON,
    GetEnterpriseServiceReviewResponseToJSON,
    GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponseFromJSON,
    GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponseToJSON,
    GetServiceCustomAppointmentsStatus200ResponseFromJSON,
    GetServiceCustomAppointmentsStatus200ResponseToJSON,
    GetServiceFreeCustomAppointmentsResponseItemFromJSON,
    GetServiceFreeCustomAppointmentsResponseItemToJSON,
    GetServiceFreeNonCustomAppointmentsResponseItemFromJSON,
    GetServiceFreeNonCustomAppointmentsResponseItemToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
    InlineObject6FromJSON,
    InlineObject6ToJSON,
    PatchCustomEnterpriseServiceRequestFromJSON,
    PatchCustomEnterpriseServiceRequestToJSON,
    PatchNonCustomEnterpriseServiceRequestFromJSON,
    PatchNonCustomEnterpriseServiceRequestToJSON,
    ServiceSearchResponseItemFromJSON,
    ServiceSearchResponseItemToJSON,
} from '../models/index';

export interface CreateCustomAppointmentsEnterpriseServiceOperationRequest {
    enterpriseId: number;
    createCustomAppointmentsEnterpriseServiceRequest: CreateCustomAppointmentsEnterpriseServiceRequest;
}

export interface CreateEnterpriseServiceReviewOperationRequest {
    serviceId: number;
    createEnterpriseServiceReviewRequest: CreateEnterpriseServiceReviewRequest;
}

export interface CreateNoCustomAppointmentsEnterpriseServiceOperationRequest {
    enterpriseId: number;
    createNoCustomAppointmentsEnterpriseServiceRequest: CreateNoCustomAppointmentsEnterpriseServiceRequest;
}

export interface GetCustomEnterpriseServiceRequest {
    serviceId: number;
}

export interface GetEnterpriseServiceRequest {
    serviceId: number;
}

export interface GetEnterpriseServicePendingAppointmentsRequest {
    serviceId: number;
}

export interface GetEnterpriseServiceReviewsRequest {
    serviceId: number;
}

export interface GetEnterpriseServiceUncancelledFutureScheduledAppointmentsRequest {
    serviceId: number;
}

export interface GetFreeNonCustomAppointmentsRequest {
    serviceId: number;
    dateInServiceTimezone: Date;
}

export interface GetFreeTimeWindowsForCustomAppointmentsRequest {
    serviceId: number;
    dateInServiceTimezone: Date;
}

export interface GetNonCustomEnterpriseServiceRequest {
    serviceId: number;
}

export interface GetServiceCustomAppointmentsStatusRequest {
    serviceId: number;
}

export interface GetUncancelledScheduledAppointmentRequest {
    appointmentId: number;
}

export interface PatchCustomEnterpriseServiceOperationRequest {
    serviceId: number;
    patchCustomEnterpriseServiceRequest: PatchCustomEnterpriseServiceRequest;
}

export interface PatchNonCustomEnterpriseServiceOperationRequest {
    serviceId: number;
    patchNonCustomEnterpriseServiceRequest: PatchNonCustomEnterpriseServiceRequest;
}

export interface SearchServicesRequest {
    preferredLongitude: number;
    preferredLatitude: number;
    cathegory: string;
    maxDistanceKm: number;
    serviceName?: string;
    enterpriseName?: string;
    startDatetimeGlobal?: Date;
    endDatetimeGlobal?: Date;
}

/**
 * 
 */
export class EnterpriseServicesApi extends runtime.BaseAPI {

    /**
     */
    async createCustomAppointmentsEnterpriseServiceRaw(requestParameters: CreateCustomAppointmentsEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['enterpriseId'] == null) {
            throw new runtime.RequiredError(
                'enterpriseId',
                'Required parameter "enterpriseId" was null or undefined when calling createCustomAppointmentsEnterpriseService().'
            );
        }

        if (requestParameters['createCustomAppointmentsEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createCustomAppointmentsEnterpriseServiceRequest',
                'Required parameter "createCustomAppointmentsEnterpriseServiceRequest" was null or undefined when calling createCustomAppointmentsEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/enterprises/{enterpriseId}/custom_appointment_services`;
        urlPath = urlPath.replace(`{${"enterpriseId"}}`, encodeURIComponent(String(requestParameters['enterpriseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomAppointmentsEnterpriseServiceRequestToJSON(requestParameters['createCustomAppointmentsEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createCustomAppointmentsEnterpriseService(enterpriseId: number, createCustomAppointmentsEnterpriseServiceRequest: CreateCustomAppointmentsEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createCustomAppointmentsEnterpriseServiceRaw({ enterpriseId: enterpriseId, createCustomAppointmentsEnterpriseServiceRequest: createCustomAppointmentsEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async createEnterpriseServiceReviewRaw(requestParameters: CreateEnterpriseServiceReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling createEnterpriseServiceReview().'
            );
        }

        if (requestParameters['createEnterpriseServiceReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'createEnterpriseServiceReviewRequest',
                'Required parameter "createEnterpriseServiceReviewRequest" was null or undefined when calling createEnterpriseServiceReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/reviews`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEnterpriseServiceReviewRequestToJSON(requestParameters['createEnterpriseServiceReviewRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createEnterpriseServiceReview(serviceId: number, createEnterpriseServiceReviewRequest: CreateEnterpriseServiceReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createEnterpriseServiceReviewRaw({ serviceId: serviceId, createEnterpriseServiceReviewRequest: createEnterpriseServiceReviewRequest }, initOverrides);
    }

    /**
     */
    async createNoCustomAppointmentsEnterpriseServiceRaw(requestParameters: CreateNoCustomAppointmentsEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['enterpriseId'] == null) {
            throw new runtime.RequiredError(
                'enterpriseId',
                'Required parameter "enterpriseId" was null or undefined when calling createNoCustomAppointmentsEnterpriseService().'
            );
        }

        if (requestParameters['createNoCustomAppointmentsEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createNoCustomAppointmentsEnterpriseServiceRequest',
                'Required parameter "createNoCustomAppointmentsEnterpriseServiceRequest" was null or undefined when calling createNoCustomAppointmentsEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/enterprises/{enterpriseId}/no_custom_appointment_services`;
        urlPath = urlPath.replace(`{${"enterpriseId"}}`, encodeURIComponent(String(requestParameters['enterpriseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNoCustomAppointmentsEnterpriseServiceRequestToJSON(requestParameters['createNoCustomAppointmentsEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createNoCustomAppointmentsEnterpriseService(enterpriseId: number, createNoCustomAppointmentsEnterpriseServiceRequest: CreateNoCustomAppointmentsEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createNoCustomAppointmentsEnterpriseServiceRaw({ enterpriseId: enterpriseId, createNoCustomAppointmentsEnterpriseServiceRequest: createNoCustomAppointmentsEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async getCustomEnterpriseServiceRaw(requestParameters: GetCustomEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEnterpriseServiceCustomServiceResponse>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getCustomEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/custom/{serviceId}`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEnterpriseServiceCustomServiceResponseFromJSON(jsonValue));
    }

    /**
     */
    async getCustomEnterpriseService(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEnterpriseServiceCustomServiceResponse> {
        const response = await this.getCustomEnterpriseServiceRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEnterpriseServiceRaw(requestParameters: GetEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEnterpriseService200Response>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEnterpriseService200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getEnterpriseService(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEnterpriseService200Response> {
        const response = await this.getEnterpriseServiceRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEnterpriseServicePendingAppointmentsRaw(requestParameters: GetEnterpriseServicePendingAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetEnterpriseServicePendingAppointmentResponse>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getEnterpriseServicePendingAppointments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/uncancelled-future-pending-appointments`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetEnterpriseServicePendingAppointmentResponseFromJSON));
    }

    /**
     */
    async getEnterpriseServicePendingAppointments(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetEnterpriseServicePendingAppointmentResponse>> {
        const response = await this.getEnterpriseServicePendingAppointmentsRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEnterpriseServiceReviewsRaw(requestParameters: GetEnterpriseServiceReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetEnterpriseServiceReviewResponse>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getEnterpriseServiceReviews().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/reviews`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetEnterpriseServiceReviewResponseFromJSON));
    }

    /**
     */
    async getEnterpriseServiceReviews(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetEnterpriseServiceReviewResponse>> {
        const response = await this.getEnterpriseServiceReviewsRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEnterpriseServiceUncancelledFutureScheduledAppointmentsRaw(requestParameters: GetEnterpriseServiceUncancelledFutureScheduledAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponse>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getEnterpriseServiceUncancelledFutureScheduledAppointments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/{serviceId}/uncancelled-future-scheduled-appointments`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponseFromJSON));
    }

    /**
     */
    async getEnterpriseServiceUncancelledFutureScheduledAppointments(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetEnterpriseServiceUncancelledFutureScheduledAppointmentResponse>> {
        const response = await this.getEnterpriseServiceUncancelledFutureScheduledAppointmentsRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFreeNonCustomAppointmentsRaw(requestParameters: GetFreeNonCustomAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetServiceFreeNonCustomAppointmentsResponseItem>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getFreeNonCustomAppointments().'
            );
        }

        if (requestParameters['dateInServiceTimezone'] == null) {
            throw new runtime.RequiredError(
                'dateInServiceTimezone',
                'Required parameter "dateInServiceTimezone" was null or undefined when calling getFreeNonCustomAppointments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateInServiceTimezone'] != null) {
            queryParameters['dateInServiceTimezone'] = (requestParameters['dateInServiceTimezone'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/free-non-custom-appointment-slots/`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetServiceFreeNonCustomAppointmentsResponseItemFromJSON));
    }

    /**
     */
    async getFreeNonCustomAppointments(serviceId: number, dateInServiceTimezone: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetServiceFreeNonCustomAppointmentsResponseItem>> {
        const response = await this.getFreeNonCustomAppointmentsRaw({ serviceId: serviceId, dateInServiceTimezone: dateInServiceTimezone }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFreeTimeWindowsForCustomAppointmentsRaw(requestParameters: GetFreeTimeWindowsForCustomAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetServiceFreeCustomAppointmentsResponseItem>>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getFreeTimeWindowsForCustomAppointments().'
            );
        }

        if (requestParameters['dateInServiceTimezone'] == null) {
            throw new runtime.RequiredError(
                'dateInServiceTimezone',
                'Required parameter "dateInServiceTimezone" was null or undefined when calling getFreeTimeWindowsForCustomAppointments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateInServiceTimezone'] != null) {
            queryParameters['dateInServiceTimezone'] = (requestParameters['dateInServiceTimezone'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/free-time-windows-for-custom-appointments`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetServiceFreeCustomAppointmentsResponseItemFromJSON));
    }

    /**
     */
    async getFreeTimeWindowsForCustomAppointments(serviceId: number, dateInServiceTimezone: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetServiceFreeCustomAppointmentsResponseItem>> {
        const response = await this.getFreeTimeWindowsForCustomAppointmentsRaw({ serviceId: serviceId, dateInServiceTimezone: dateInServiceTimezone }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getNonCustomEnterpriseServiceRaw(requestParameters: GetNonCustomEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEnterpriseServiceNonCustomServiceResponse>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getNonCustomEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/non-custom/{serviceId}`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEnterpriseServiceNonCustomServiceResponseFromJSON(jsonValue));
    }

    /**
     */
    async getNonCustomEnterpriseService(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEnterpriseServiceNonCustomServiceResponse> {
        const response = await this.getNonCustomEnterpriseServiceRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceCustomAppointmentsStatusRaw(requestParameters: GetServiceCustomAppointmentsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetServiceCustomAppointmentsStatus200Response>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling getServiceCustomAppointmentsStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/{serviceId}/custom-appointments-or-not`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetServiceCustomAppointmentsStatus200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceCustomAppointmentsStatus(serviceId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetServiceCustomAppointmentsStatus200Response> {
        const response = await this.getServiceCustomAppointmentsStatusRaw({ serviceId: serviceId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async getUncancelledScheduledAppointmentRaw(requestParameters: GetUncancelledScheduledAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetEnterpriseServicePendingAppointmentResponse>>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling getUncancelledScheduledAppointment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/uncancelled-scheduled-appointments/{appointmentId}`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetEnterpriseServicePendingAppointmentResponseFromJSON));
    }

    /**
     */
    async getUncancelledScheduledAppointment(appointmentId: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetEnterpriseServicePendingAppointmentResponse>> {
        const response = await this.getUncancelledScheduledAppointmentRaw({ appointmentId: appointmentId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async patchCustomEnterpriseServiceRaw(requestParameters: PatchCustomEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling patchCustomEnterpriseService().'
            );
        }

        if (requestParameters['patchCustomEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'patchCustomEnterpriseServiceRequest',
                'Required parameter "patchCustomEnterpriseServiceRequest" was null or undefined when calling patchCustomEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/custom/{serviceId}`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchCustomEnterpriseServiceRequestToJSON(requestParameters['patchCustomEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async patchCustomEnterpriseService(serviceId: number, patchCustomEnterpriseServiceRequest: PatchCustomEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchCustomEnterpriseServiceRaw({ serviceId: serviceId, patchCustomEnterpriseServiceRequest: patchCustomEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async patchNonCustomEnterpriseServiceRaw(requestParameters: PatchNonCustomEnterpriseServiceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serviceId'] == null) {
            throw new runtime.RequiredError(
                'serviceId',
                'Required parameter "serviceId" was null or undefined when calling patchNonCustomEnterpriseService().'
            );
        }

        if (requestParameters['patchNonCustomEnterpriseServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'patchNonCustomEnterpriseServiceRequest',
                'Required parameter "patchNonCustomEnterpriseServiceRequest" was null or undefined when calling patchNonCustomEnterpriseService().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/services/non-custom/{serviceId}`;
        urlPath = urlPath.replace(`{${"serviceId"}}`, encodeURIComponent(String(requestParameters['serviceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchNonCustomEnterpriseServiceRequestToJSON(requestParameters['patchNonCustomEnterpriseServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async patchNonCustomEnterpriseService(serviceId: number, patchNonCustomEnterpriseServiceRequest: PatchNonCustomEnterpriseServiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchNonCustomEnterpriseServiceRaw({ serviceId: serviceId, patchNonCustomEnterpriseServiceRequest: patchNonCustomEnterpriseServiceRequest }, initOverrides);
    }

    /**
     */
    async searchServicesRaw(requestParameters: SearchServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceSearchResponseItem>>> {
        if (requestParameters['preferredLongitude'] == null) {
            throw new runtime.RequiredError(
                'preferredLongitude',
                'Required parameter "preferredLongitude" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['preferredLatitude'] == null) {
            throw new runtime.RequiredError(
                'preferredLatitude',
                'Required parameter "preferredLatitude" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['cathegory'] == null) {
            throw new runtime.RequiredError(
                'cathegory',
                'Required parameter "cathegory" was null or undefined when calling searchServices().'
            );
        }

        if (requestParameters['maxDistanceKm'] == null) {
            throw new runtime.RequiredError(
                'maxDistanceKm',
                'Required parameter "maxDistanceKm" was null or undefined when calling searchServices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['serviceName'] != null) {
            queryParameters['serviceName'] = requestParameters['serviceName'];
        }

        if (requestParameters['enterpriseName'] != null) {
            queryParameters['enterpriseName'] = requestParameters['enterpriseName'];
        }

        if (requestParameters['startDatetimeGlobal'] != null) {
            queryParameters['startDatetimeGlobal'] = (requestParameters['startDatetimeGlobal'] as any).toISOString();
        }

        if (requestParameters['endDatetimeGlobal'] != null) {
            queryParameters['endDatetimeGlobal'] = (requestParameters['endDatetimeGlobal'] as any).toISOString();
        }

        if (requestParameters['preferredLongitude'] != null) {
            queryParameters['preferredLongitude'] = requestParameters['preferredLongitude'];
        }

        if (requestParameters['preferredLatitude'] != null) {
            queryParameters['preferredLatitude'] = requestParameters['preferredLatitude'];
        }

        if (requestParameters['cathegory'] != null) {
            queryParameters['cathegory'] = requestParameters['cathegory'];
        }

        if (requestParameters['maxDistanceKm'] != null) {
            queryParameters['maxDistanceKm'] = requestParameters['maxDistanceKm'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceSearchResponseItemFromJSON));
    }

    /**
     */
    async searchServices(preferredLongitude: number, preferredLatitude: number, cathegory: string, maxDistanceKm: number, serviceName?: string, enterpriseName?: string, startDatetimeGlobal?: Date, endDatetimeGlobal?: Date, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceSearchResponseItem>> {
        const response = await this.searchServicesRaw({ preferredLongitude: preferredLongitude, preferredLatitude: preferredLatitude, cathegory: cathegory, maxDistanceKm: maxDistanceKm, serviceName: serviceName, enterpriseName: enterpriseName, startDatetimeGlobal: startDatetimeGlobal, endDatetimeGlobal: endDatetimeGlobal }, initOverrides);
        return await response.value();
    }

}
