/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetMeResponseEnterpreneur,
  InlineObject,
} from '../models/index';
import {
    GetMeResponseEnterpreneurFromJSON,
    GetMeResponseEnterpreneurToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

/**
 * 
 */
export class MeApi extends runtime.BaseAPI {

    /**
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMeResponseEnterpreneur>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // JwtBearerAuth authentication
        }


        let urlPath = `/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMeResponseEnterpreneurFromJSON(jsonValue));
    }

    /**
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMeResponseEnterpreneur> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

}
