/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateIndependentEndUserRequest,
  GetRegularAdminResponse,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject3,
  InlineObject4,
} from '../models/index';
import {
    CreateIndependentEndUserRequestFromJSON,
    CreateIndependentEndUserRequestToJSON,
    GetRegularAdminResponseFromJSON,
    GetRegularAdminResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject3FromJSON,
    InlineObject3ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
} from '../models/index';

export interface CreateRegularAdminRequest {
    createIndependentEndUserRequest: CreateIndependentEndUserRequest;
}

/**
 * 
 */
export class RegularAdminsApi extends runtime.BaseAPI {

    /**
     */
    async createRegularAdminRaw(requestParameters: CreateRegularAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createIndependentEndUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createIndependentEndUserRequest',
                'Required parameter "createIndependentEndUserRequest" was null or undefined when calling createRegularAdmin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/regular-admins`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIndependentEndUserRequestToJSON(requestParameters['createIndependentEndUserRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createRegularAdmin(createIndependentEndUserRequest: CreateIndependentEndUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createRegularAdminRaw({ createIndependentEndUserRequest: createIndependentEndUserRequest }, initOverrides);
    }

    /**
     */
    async getRegularAdminsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRegularAdminResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/regular-admins`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRegularAdminResponseFromJSON(jsonValue));
    }

    /**
     */
    async getRegularAdmins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRegularAdminResponse> {
        const response = await this.getRegularAdminsRaw(initOverrides);
        return await response.value();
    }

}
