/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateReportRequest,
  GetUnresolvedReports200ResponseInner,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject4,
} from '../models/index';
import {
    CreateReportRequestFromJSON,
    CreateReportRequestToJSON,
    GetUnresolvedReports200ResponseInnerFromJSON,
    GetUnresolvedReports200ResponseInnerToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
} from '../models/index';

export interface CreateReportOperationRequest {
    createReportRequest: CreateReportRequest;
}

export interface ResolveReportRequest {
    reportId?: number;
}

/**
 * 
 */
export class ReportApi extends runtime.BaseAPI {

    /**
     */
    async createReportRaw(requestParameters: CreateReportOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createReportRequest'] == null) {
            throw new runtime.RequiredError(
                'createReportRequest',
                'Required parameter "createReportRequest" was null or undefined when calling createReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reports`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReportRequestToJSON(requestParameters['createReportRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createReport(createReportRequest: CreateReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createReportRaw({ createReportRequest: createReportRequest }, initOverrides);
    }

    /**
     */
    async getUnresolvedReportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetUnresolvedReports200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reports/unresolved`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetUnresolvedReports200ResponseInnerFromJSON));
    }

    /**
     */
    async getUnresolvedReports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetUnresolvedReports200ResponseInner>> {
        const response = await this.getUnresolvedReportsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async resolveReportRaw(requestParameters: ResolveReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['reportId'] != null) {
            queryParameters['reportId'] = requestParameters['reportId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reports/resolve`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resolveReport(reportId?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resolveReportRaw({ reportId: reportId }, initOverrides);
    }

}
