/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdyenAmount
 */
export interface AdyenAmount {
    /**
     * 
     * @type {string}
     * @memberof AdyenAmount
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof AdyenAmount
     */
    value: number;
}

/**
 * Check if a given object implements the AdyenAmount interface.
 */
export function instanceOfAdyenAmount(value: object): value is AdyenAmount {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AdyenAmountFromJSON(json: any): AdyenAmount {
    return AdyenAmountFromJSONTyped(json, false);
}

export function AdyenAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'value': json['value'],
    };
}

export function AdyenAmountToJSON(json: any): AdyenAmount {
    return AdyenAmountToJSONTyped(json, false);
}

export function AdyenAmountToJSONTyped(value?: AdyenAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'value': value['value'],
    };
}

