/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdyenWebhookRequestNotificationItem } from './AdyenWebhookRequestNotificationItem';
import {
    AdyenWebhookRequestNotificationItemFromJSON,
    AdyenWebhookRequestNotificationItemFromJSONTyped,
    AdyenWebhookRequestNotificationItemToJSON,
    AdyenWebhookRequestNotificationItemToJSONTyped,
} from './AdyenWebhookRequestNotificationItem';

/**
 * 
 * @export
 * @interface AdyenWebhookRequest
 */
export interface AdyenWebhookRequest {
    /**
     * 
     * @type {boolean}
     * @memberof AdyenWebhookRequest
     */
    live: boolean;
    /**
     * 
     * @type {Array<AdyenWebhookRequestNotificationItem>}
     * @memberof AdyenWebhookRequest
     */
    notificationItems: Array<AdyenWebhookRequestNotificationItem>;
}

/**
 * Check if a given object implements the AdyenWebhookRequest interface.
 */
export function instanceOfAdyenWebhookRequest(value: object): value is AdyenWebhookRequest {
    if (!('live' in value) || value['live'] === undefined) return false;
    if (!('notificationItems' in value) || value['notificationItems'] === undefined) return false;
    return true;
}

export function AdyenWebhookRequestFromJSON(json: any): AdyenWebhookRequest {
    return AdyenWebhookRequestFromJSONTyped(json, false);
}

export function AdyenWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'live': json['live'],
        'notificationItems': ((json['notificationItems'] as Array<any>).map(AdyenWebhookRequestNotificationItemFromJSON)),
    };
}

export function AdyenWebhookRequestToJSON(json: any): AdyenWebhookRequest {
    return AdyenWebhookRequestToJSONTyped(json, false);
}

export function AdyenWebhookRequestToJSONTyped(value?: AdyenWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'live': value['live'],
        'notificationItems': ((value['notificationItems'] as Array<any>).map(AdyenWebhookRequestNotificationItemToJSON)),
    };
}

