/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdyenPaymentMethod
 */
export interface AdyenPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof AdyenPaymentMethod
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof AdyenPaymentMethod
     */
    scheme: string;
}

/**
 * Check if a given object implements the AdyenPaymentMethod interface.
 */
export function instanceOfAdyenPaymentMethod(value: object): value is AdyenPaymentMethod {
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('scheme' in value) || value['scheme'] === undefined) return false;
    return true;
}

export function AdyenPaymentMethodFromJSON(json: any): AdyenPaymentMethod {
    return AdyenPaymentMethodFromJSONTyped(json, false);
}

export function AdyenPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenPaymentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'brand': json['brand'],
        'scheme': json['scheme'],
    };
}

export function AdyenPaymentMethodToJSON(json: any): AdyenPaymentMethod {
    return AdyenPaymentMethodToJSONTyped(json, false);
}

export function AdyenPaymentMethodToJSONTyped(value?: AdyenPaymentMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brand': value['brand'],
        'scheme': value['scheme'],
    };
}

