/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdyenWebhookRequestNotificationItemAmount
 */
export interface AdyenWebhookRequestNotificationItemAmount {
    /**
     * 
     * @type {number}
     * @memberof AdyenWebhookRequestNotificationItemAmount
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof AdyenWebhookRequestNotificationItemAmount
     */
    currency: string;
}

/**
 * Check if a given object implements the AdyenWebhookRequestNotificationItemAmount interface.
 */
export function instanceOfAdyenWebhookRequestNotificationItemAmount(value: object): value is AdyenWebhookRequestNotificationItemAmount {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function AdyenWebhookRequestNotificationItemAmountFromJSON(json: any): AdyenWebhookRequestNotificationItemAmount {
    return AdyenWebhookRequestNotificationItemAmountFromJSONTyped(json, false);
}

export function AdyenWebhookRequestNotificationItemAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenWebhookRequestNotificationItemAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'currency': json['currency'],
    };
}

export function AdyenWebhookRequestNotificationItemAmountToJSON(json: any): AdyenWebhookRequestNotificationItemAmount {
    return AdyenWebhookRequestNotificationItemAmountToJSONTyped(json, false);
}

export function AdyenWebhookRequestNotificationItemAmountToJSONTyped(value?: AdyenWebhookRequestNotificationItemAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'currency': value['currency'],
    };
}

