/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdyenAmount } from './AdyenAmount';
import {
    AdyenAmountFromJSON,
    AdyenAmountFromJSONTyped,
    AdyenAmountToJSON,
    AdyenAmountToJSONTyped,
} from './AdyenAmount';
import type { AdyenWebhookRequestNotificationItemAdditionalData } from './AdyenWebhookRequestNotificationItemAdditionalData';
import {
    AdyenWebhookRequestNotificationItemAdditionalDataFromJSON,
    AdyenWebhookRequestNotificationItemAdditionalDataFromJSONTyped,
    AdyenWebhookRequestNotificationItemAdditionalDataToJSON,
    AdyenWebhookRequestNotificationItemAdditionalDataToJSONTyped,
} from './AdyenWebhookRequestNotificationItemAdditionalData';

/**
 * 
 * @export
 * @interface AdyenWebhookRequestNotificationItem
 */
export interface AdyenWebhookRequestNotificationItem {
    /**
     * 
     * @type {AdyenWebhookRequestNotificationItemAdditionalData}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    additionalData?: AdyenWebhookRequestNotificationItemAdditionalData;
    /**
     * 
     * @type {string}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    eventCode: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    success: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    eventDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    merchantAccountCode: string;
    /**
     * 
     * @type {string}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    pspReference: string;
    /**
     * 
     * @type {string}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    merchantReference: string;
    /**
     * 
     * @type {AdyenAmount}
     * @memberof AdyenWebhookRequestNotificationItem
     */
    amount: AdyenAmount;
}

/**
 * Check if a given object implements the AdyenWebhookRequestNotificationItem interface.
 */
export function instanceOfAdyenWebhookRequestNotificationItem(value: object): value is AdyenWebhookRequestNotificationItem {
    if (!('eventCode' in value) || value['eventCode'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('eventDate' in value) || value['eventDate'] === undefined) return false;
    if (!('merchantAccountCode' in value) || value['merchantAccountCode'] === undefined) return false;
    if (!('pspReference' in value) || value['pspReference'] === undefined) return false;
    if (!('merchantReference' in value) || value['merchantReference'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AdyenWebhookRequestNotificationItemFromJSON(json: any): AdyenWebhookRequestNotificationItem {
    return AdyenWebhookRequestNotificationItemFromJSONTyped(json, false);
}

export function AdyenWebhookRequestNotificationItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdyenWebhookRequestNotificationItem {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalData': json['additionalData'] == null ? undefined : AdyenWebhookRequestNotificationItemAdditionalDataFromJSON(json['additionalData']),
        'eventCode': json['eventCode'],
        'success': json['success'],
        'eventDate': (new Date(json['eventDate'])),
        'merchantAccountCode': json['merchantAccountCode'],
        'pspReference': json['pspReference'],
        'merchantReference': json['merchantReference'],
        'amount': AdyenAmountFromJSON(json['amount']),
    };
}

export function AdyenWebhookRequestNotificationItemToJSON(json: any): AdyenWebhookRequestNotificationItem {
    return AdyenWebhookRequestNotificationItemToJSONTyped(json, false);
}

export function AdyenWebhookRequestNotificationItemToJSONTyped(value?: AdyenWebhookRequestNotificationItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalData': AdyenWebhookRequestNotificationItemAdditionalDataToJSON(value['additionalData']),
        'eventCode': value['eventCode'],
        'success': value['success'],
        'eventDate': ((value['eventDate']).toISOString()),
        'merchantAccountCode': value['merchantAccountCode'],
        'pspReference': value['pspReference'],
        'merchantReference': value['merchantReference'],
        'amount': AdyenAmountToJSON(value['amount']),
    };
}

