/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckIndependentEndUserEmailExists200Response
 */
export interface CheckIndependentEndUserEmailExists200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckIndependentEndUserEmailExists200Response
     */
    isExisting: boolean;
}

/**
 * Check if a given object implements the CheckIndependentEndUserEmailExists200Response interface.
 */
export function instanceOfCheckIndependentEndUserEmailExists200Response(value: object): value is CheckIndependentEndUserEmailExists200Response {
    if (!('isExisting' in value) || value['isExisting'] === undefined) return false;
    return true;
}

export function CheckIndependentEndUserEmailExists200ResponseFromJSON(json: any): CheckIndependentEndUserEmailExists200Response {
    return CheckIndependentEndUserEmailExists200ResponseFromJSONTyped(json, false);
}

export function CheckIndependentEndUserEmailExists200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckIndependentEndUserEmailExists200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'isExisting': json['isExisting'],
    };
}

export function CheckIndependentEndUserEmailExists200ResponseToJSON(json: any): CheckIndependentEndUserEmailExists200Response {
    return CheckIndependentEndUserEmailExists200ResponseToJSONTyped(json, false);
}

export function CheckIndependentEndUserEmailExists200ResponseToJSONTyped(value?: CheckIndependentEndUserEmailExists200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isExisting': value['isExisting'],
    };
}

