/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRegularAdminRequest
 */
export interface CreateRegularAdminRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRegularAdminRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegularAdminRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegularAdminRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRegularAdminRequest
     */
    password: string;
}

/**
 * Check if a given object implements the CreateRegularAdminRequest interface.
 */
export function instanceOfCreateRegularAdminRequest(value: object): value is CreateRegularAdminRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateRegularAdminRequestFromJSON(json: any): CreateRegularAdminRequest {
    return CreateRegularAdminRequestFromJSONTyped(json, false);
}

export function CreateRegularAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRegularAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function CreateRegularAdminRequestToJSON(json: any): CreateRegularAdminRequest {
    return CreateRegularAdminRequestToJSONTyped(json, false);
}

export function CreateRegularAdminRequestToJSONTyped(value?: CreateRegularAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'username': value['username'],
        'password': value['password'],
    };
}

