/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface CreateCustomAppointmentRequest
 */
export interface CreateCustomAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentRequest
     */
    startDatetimeShopLocal: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentRequest
     */
    endDatetimeShopLocal: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCustomAppointmentRequest
     */
    price?: number;
    /**
     * 
     * @type {Location}
     * @memberof CreateCustomAppointmentRequest
     */
    location: Location;
}

/**
 * Check if a given object implements the CreateCustomAppointmentRequest interface.
 */
export function instanceOfCreateCustomAppointmentRequest(value: object): value is CreateCustomAppointmentRequest {
    if (!('startDatetimeShopLocal' in value) || value['startDatetimeShopLocal'] === undefined) return false;
    if (!('endDatetimeShopLocal' in value) || value['endDatetimeShopLocal'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function CreateCustomAppointmentRequestFromJSON(json: any): CreateCustomAppointmentRequest {
    return CreateCustomAppointmentRequestFromJSONTyped(json, false);
}

export function CreateCustomAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomAppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDatetimeShopLocal': json['startDatetimeShopLocal'],
        'endDatetimeShopLocal': json['endDatetimeShopLocal'],
        'price': json['price'] == null ? undefined : json['price'],
        'location': LocationFromJSON(json['location']),
    };
}

export function CreateCustomAppointmentRequestToJSON(json: any): CreateCustomAppointmentRequest {
    return CreateCustomAppointmentRequestToJSONTyped(json, false);
}

export function CreateCustomAppointmentRequestToJSONTyped(value?: CreateCustomAppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDatetimeShopLocal': value['startDatetimeShopLocal'],
        'endDatetimeShopLocal': value['endDatetimeShopLocal'],
        'price': value['price'],
        'location': LocationToJSON(value['location']),
    };
}

