/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseEmployeeResponseUser
 */
export interface CreateEnterpriseEmployeeResponseUser {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseEmployeeResponseUser
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseEmployeeResponseUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseEmployeeResponseUser
     */
    username: string;
}

/**
 * Check if a given object implements the CreateEnterpriseEmployeeResponseUser interface.
 */
export function instanceOfCreateEnterpriseEmployeeResponseUser(value: object): value is CreateEnterpriseEmployeeResponseUser {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateEnterpriseEmployeeResponseUserFromJSON(json: any): CreateEnterpriseEmployeeResponseUser {
    return CreateEnterpriseEmployeeResponseUserFromJSONTyped(json, false);
}

export function CreateEnterpriseEmployeeResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseEmployeeResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'username': json['username'],
    };
}

export function CreateEnterpriseEmployeeResponseUserToJSON(json: any): CreateEnterpriseEmployeeResponseUser {
    return CreateEnterpriseEmployeeResponseUserToJSONTyped(json, false);
}

export function CreateEnterpriseEmployeeResponseUserToJSONTyped(value?: CreateEnterpriseEmployeeResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'username': value['username'],
    };
}

