/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Slot } from './Slot';
import {
    SlotFromJSON,
    SlotFromJSONTyped,
    SlotToJSON,
    SlotToJSONTyped,
} from './Slot';

/**
 * 
 * @export
 * @interface CreateEnterpriseServiceRequestSlotsInner
 */
export interface CreateEnterpriseServiceRequestSlotsInner {
    /**
     * 
     * @type {Slot}
     * @memberof CreateEnterpriseServiceRequestSlotsInner
     */
    items?: Slot;
}

/**
 * Check if a given object implements the CreateEnterpriseServiceRequestSlotsInner interface.
 */
export function instanceOfCreateEnterpriseServiceRequestSlotsInner(value: object): value is CreateEnterpriseServiceRequestSlotsInner {
    return true;
}

export function CreateEnterpriseServiceRequestSlotsInnerFromJSON(json: any): CreateEnterpriseServiceRequestSlotsInner {
    return CreateEnterpriseServiceRequestSlotsInnerFromJSONTyped(json, false);
}

export function CreateEnterpriseServiceRequestSlotsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseServiceRequestSlotsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : SlotFromJSON(json['items']),
    };
}

export function CreateEnterpriseServiceRequestSlotsInnerToJSON(json: any): CreateEnterpriseServiceRequestSlotsInner {
    return CreateEnterpriseServiceRequestSlotsInnerToJSONTyped(json, false);
}

export function CreateEnterpriseServiceRequestSlotsInnerToJSONTyped(value?: CreateEnterpriseServiceRequestSlotsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': SlotToJSON(value['items']),
    };
}

