/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateIndependentEndUserResponseUser } from './CreateIndependentEndUserResponseUser';
import {
    CreateIndependentEndUserResponseUserFromJSON,
    CreateIndependentEndUserResponseUserFromJSONTyped,
    CreateIndependentEndUserResponseUserToJSON,
    CreateIndependentEndUserResponseUserToJSONTyped,
} from './CreateIndependentEndUserResponseUser';

/**
 * 
 * @export
 * @interface CreateIndependentEndUserResponse
 */
export interface CreateIndependentEndUserResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateIndependentEndUserResponse
     */
    accessToken: string;
    /**
     * 
     * @type {CreateIndependentEndUserResponseUser}
     * @memberof CreateIndependentEndUserResponse
     */
    user: CreateIndependentEndUserResponseUser;
}

/**
 * Check if a given object implements the CreateIndependentEndUserResponse interface.
 */
export function instanceOfCreateIndependentEndUserResponse(value: object): value is CreateIndependentEndUserResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function CreateIndependentEndUserResponseFromJSON(json: any): CreateIndependentEndUserResponse {
    return CreateIndependentEndUserResponseFromJSONTyped(json, false);
}

export function CreateIndependentEndUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndependentEndUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'user': CreateIndependentEndUserResponseUserFromJSON(json['user']),
    };
}

export function CreateIndependentEndUserResponseToJSON(json: any): CreateIndependentEndUserResponse {
    return CreateIndependentEndUserResponseToJSONTyped(json, false);
}

export function CreateIndependentEndUserResponseToJSONTyped(value?: CreateIndependentEndUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'user': CreateIndependentEndUserResponseUserToJSON(value['user']),
    };
}

