/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEntrepreneurRequest
 */
export interface CreateEntrepreneurRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    dateOfBirth: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntrepreneurRequest
     */
    iban: string;
}

/**
 * Check if a given object implements the CreateEntrepreneurRequest interface.
 */
export function instanceOfCreateEntrepreneurRequest(value: object): value is CreateEntrepreneurRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('street' in value) || value['street'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('iban' in value) || value['iban'] === undefined) return false;
    return true;
}

export function CreateEntrepreneurRequestFromJSON(json: any): CreateEntrepreneurRequest {
    return CreateEntrepreneurRequestFromJSONTyped(json, false);
}

export function CreateEntrepreneurRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEntrepreneurRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'password': json['password'],
        'dateOfBirth': json['dateOfBirth'],
        'country': json['country'],
        'city': json['city'],
        'street': json['street'],
        'postalCode': json['postalCode'],
        'iban': json['iban'],
    };
}

export function CreateEntrepreneurRequestToJSON(json: any): CreateEntrepreneurRequest {
    return CreateEntrepreneurRequestToJSONTyped(json, false);
}

export function CreateEntrepreneurRequestToJSONTyped(value?: CreateEntrepreneurRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'password': value['password'],
        'dateOfBirth': value['dateOfBirth'],
        'country': value['country'],
        'city': value['city'],
        'street': value['street'],
        'postalCode': value['postalCode'],
        'iban': value['iban'],
    };
}

