/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReportRequest
 */
export interface CreateReportRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    reportSubjectType: string;
    /**
     * 
     * @type {number}
     * @memberof CreateReportRequest
     */
    reportSubjectId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReportRequest
     */
    text: string;
}

/**
 * Check if a given object implements the CreateReportRequest interface.
 */
export function instanceOfCreateReportRequest(value: object): value is CreateReportRequest {
    if (!('reportSubjectType' in value) || value['reportSubjectType'] === undefined) return false;
    if (!('reportSubjectId' in value) || value['reportSubjectId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreateReportRequestFromJSON(json: any): CreateReportRequest {
    return CreateReportRequestFromJSONTyped(json, false);
}

export function CreateReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reportSubjectType': json['reportSubjectType'],
        'reportSubjectId': json['reportSubjectId'],
        'text': json['text'],
    };
}

export function CreateReportRequestToJSON(json: any): CreateReportRequest {
    return CreateReportRequestToJSONTyped(json, false);
}

export function CreateReportRequestToJSONTyped(value?: CreateReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportSubjectType': value['reportSubjectType'],
        'reportSubjectId': value['reportSubjectId'],
        'text': value['text'],
    };
}

