/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdyenSessionRequest
 */
export interface CreateAdyenSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAdyenSessionRequest
     */
    returnUrl: string;
}

/**
 * Check if a given object implements the CreateAdyenSessionRequest interface.
 */
export function instanceOfCreateAdyenSessionRequest(value: object): value is CreateAdyenSessionRequest {
    if (!('returnUrl' in value) || value['returnUrl'] === undefined) return false;
    return true;
}

export function CreateAdyenSessionRequestFromJSON(json: any): CreateAdyenSessionRequest {
    return CreateAdyenSessionRequestFromJSONTyped(json, false);
}

export function CreateAdyenSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdyenSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'returnUrl': json['returnUrl'],
    };
}

export function CreateAdyenSessionRequestToJSON(json: any): CreateAdyenSessionRequest {
    return CreateAdyenSessionRequestToJSONTyped(json, false);
}

export function CreateAdyenSessionRequestToJSONTyped(value?: CreateAdyenSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'returnUrl': value['returnUrl'],
    };
}

