/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateIndependentEndUserResponseUser
 */
export interface CreateIndependentEndUserResponseUser {
    /**
     * 
     * @type {string}
     * @memberof CreateIndependentEndUserResponseUser
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateIndependentEndUserResponseUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateIndependentEndUserResponseUser
     */
    email: string;
}

/**
 * Check if a given object implements the CreateIndependentEndUserResponseUser interface.
 */
export function instanceOfCreateIndependentEndUserResponseUser(value: object): value is CreateIndependentEndUserResponseUser {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateIndependentEndUserResponseUserFromJSON(json: any): CreateIndependentEndUserResponseUser {
    return CreateIndependentEndUserResponseUserFromJSONTyped(json, false);
}

export function CreateIndependentEndUserResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIndependentEndUserResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
    };
}

export function CreateIndependentEndUserResponseUserToJSON(json: any): CreateIndependentEndUserResponseUser {
    return CreateIndependentEndUserResponseUserToJSONTyped(json, false);
}

export function CreateIndependentEndUserResponseUserToJSONTyped(value?: CreateIndependentEndUserResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

