/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type CreateEnterpriseServiceLocation
 * 
 * @export
 */
export type CreateEnterpriseServiceLocation = boolean | string;

export function CreateEnterpriseServiceLocationFromJSON(json: any): CreateEnterpriseServiceLocation {
    return CreateEnterpriseServiceLocationFromJSONTyped(json, false);
}

export function CreateEnterpriseServiceLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseServiceLocation {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function CreateEnterpriseServiceLocationToJSON(json: any): any {
    return CreateEnterpriseServiceLocationToJSONTyped(json, false);
}

export function CreateEnterpriseServiceLocationToJSONTyped(value?: CreateEnterpriseServiceLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

