/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterprise
 */
export interface CreateEnterprise {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterprise
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterprise
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterprise
     */
    location: string;
}

/**
 * Check if a given object implements the CreateEnterprise interface.
 */
export function instanceOfCreateEnterprise(value: object): value is CreateEnterprise {
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function CreateEnterpriseFromJSON(json: any): CreateEnterprise {
    return CreateEnterpriseFromJSONTyped(json, false);
}

export function CreateEnterpriseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterprise {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseName': json['enterpriseName'],
        'description': json['description'],
        'location': json['location'],
    };
}

export function CreateEnterpriseToJSON(json: any): CreateEnterprise {
    return CreateEnterpriseToJSONTyped(json, false);
}

export function CreateEnterpriseToJSONTyped(value?: CreateEnterprise | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseName': value['enterpriseName'],
        'description': value['description'],
        'location': value['location'],
    };
}

