/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseServiceRequest
 */
export interface CreateEnterpriseServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseServiceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseServiceRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseServiceRequest
     */
    location: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEnterpriseServiceRequest
     */
    takesCustomAppointments: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateEnterpriseServiceRequest
     */
    price: number;
    /**
     * currency ISO code
     * @type {string}
     * @memberof CreateEnterpriseServiceRequest
     */
    currency: string;
}

/**
 * Check if a given object implements the CreateEnterpriseServiceRequest interface.
 */
export function instanceOfCreateEnterpriseServiceRequest(value: object): value is CreateEnterpriseServiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('takesCustomAppointments' in value) || value['takesCustomAppointments'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CreateEnterpriseServiceRequestFromJSON(json: any): CreateEnterpriseServiceRequest {
    return CreateEnterpriseServiceRequestFromJSONTyped(json, false);
}

export function CreateEnterpriseServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'location': json['location'],
        'takesCustomAppointments': json['takesCustomAppointments'],
        'price': json['price'],
        'currency': json['currency'],
    };
}

export function CreateEnterpriseServiceRequestToJSON(json: any): CreateEnterpriseServiceRequest {
    return CreateEnterpriseServiceRequestToJSONTyped(json, false);
}

export function CreateEnterpriseServiceRequestToJSONTyped(value?: CreateEnterpriseServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'takesCustomAppointments': value['takesCustomAppointments'],
        'price': value['price'],
        'currency': value['currency'],
    };
}

