/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Slot } from './Slot';
import {
    SlotFromJSON,
    SlotFromJSONTyped,
    SlotToJSON,
    SlotToJSONTyped,
} from './Slot';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface CreateNoCustomAppointmentsEnterpriseServiceRequest
 */
export interface CreateNoCustomAppointmentsEnterpriseServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    description: string;
    /**
     * 
     * @type {Location}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    location: Location;
    /**
     * 
     * @type {string}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    timeZone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    cathegory: string;
    /**
     * 
     * @type {number}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    price: number;
    /**
     * currency ISO code
     * @type {string}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    currency: string;
    /**
     * 
     * @type {Array<Slot>}
     * @memberof CreateNoCustomAppointmentsEnterpriseServiceRequest
     */
    slots: Array<Slot>;
}

/**
 * Check if a given object implements the CreateNoCustomAppointmentsEnterpriseServiceRequest interface.
 */
export function instanceOfCreateNoCustomAppointmentsEnterpriseServiceRequest(value: object): value is CreateNoCustomAppointmentsEnterpriseServiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('timeZone' in value) || value['timeZone'] === undefined) return false;
    if (!('cathegory' in value) || value['cathegory'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    return true;
}

export function CreateNoCustomAppointmentsEnterpriseServiceRequestFromJSON(json: any): CreateNoCustomAppointmentsEnterpriseServiceRequest {
    return CreateNoCustomAppointmentsEnterpriseServiceRequestFromJSONTyped(json, false);
}

export function CreateNoCustomAppointmentsEnterpriseServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNoCustomAppointmentsEnterpriseServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'location': LocationFromJSON(json['location']),
        'timeZone': json['timeZone'],
        'cathegory': json['cathegory'],
        'price': json['price'],
        'currency': json['currency'],
        'slots': ((json['slots'] as Array<any>).map(SlotFromJSON)),
    };
}

export function CreateNoCustomAppointmentsEnterpriseServiceRequestToJSON(json: any): CreateNoCustomAppointmentsEnterpriseServiceRequest {
    return CreateNoCustomAppointmentsEnterpriseServiceRequestToJSONTyped(json, false);
}

export function CreateNoCustomAppointmentsEnterpriseServiceRequestToJSONTyped(value?: CreateNoCustomAppointmentsEnterpriseServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timeZone': value['timeZone'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currency': value['currency'],
        'slots': ((value['slots'] as Array<any>).map(SlotToJSON)),
    };
}

