/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseRequest
 */
export interface CreateEnterpriseRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    location: string;
    /**
     * 
     * @type {Blob}
     * @memberof CreateEnterpriseRequest
     */
    logo: Blob;
    /**
     * 
     * @type {Blob}
     * @memberof CreateEnterpriseRequest
     */
    backgroundPhoto: Blob;
}

/**
 * Check if a given object implements the CreateEnterpriseRequest interface.
 */
export function instanceOfCreateEnterpriseRequest(value: object): value is CreateEnterpriseRequest {
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('backgroundPhoto' in value) || value['backgroundPhoto'] === undefined) return false;
    return true;
}

export function CreateEnterpriseRequestFromJSON(json: any): CreateEnterpriseRequest {
    return CreateEnterpriseRequestFromJSONTyped(json, false);
}

export function CreateEnterpriseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseName': json['enterpriseName'],
        'description': json['description'],
        'location': json['location'],
        'logo': json['logo'],
        'backgroundPhoto': json['backgroundPhoto'],
    };
}

export function CreateEnterpriseRequestToJSON(json: any): CreateEnterpriseRequest {
    return CreateEnterpriseRequestToJSONTyped(json, false);
}

export function CreateEnterpriseRequestToJSONTyped(value?: CreateEnterpriseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseName': value['enterpriseName'],
        'description': value['description'],
        'location': value['location'],
        'logo': value['logo'],
        'backgroundPhoto': value['backgroundPhoto'],
    };
}

