/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNonCustomAppointmentRequest
 */
export interface CreateNonCustomAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNonCustomAppointmentRequest
     */
    startDatetimeEnterpriseServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNonCustomAppointmentRequest
     */
    endDatetimeEnterpriseServiceLocal: string;
}

/**
 * Check if a given object implements the CreateNonCustomAppointmentRequest interface.
 */
export function instanceOfCreateNonCustomAppointmentRequest(value: object): value is CreateNonCustomAppointmentRequest {
    if (!('startDatetimeEnterpriseServiceLocal' in value) || value['startDatetimeEnterpriseServiceLocal'] === undefined) return false;
    if (!('endDatetimeEnterpriseServiceLocal' in value) || value['endDatetimeEnterpriseServiceLocal'] === undefined) return false;
    return true;
}

export function CreateNonCustomAppointmentRequestFromJSON(json: any): CreateNonCustomAppointmentRequest {
    return CreateNonCustomAppointmentRequestFromJSONTyped(json, false);
}

export function CreateNonCustomAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNonCustomAppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDatetimeEnterpriseServiceLocal': json['startDatetimeEnterpriseServiceLocal'],
        'endDatetimeEnterpriseServiceLocal': json['endDatetimeEnterpriseServiceLocal'],
    };
}

export function CreateNonCustomAppointmentRequestToJSON(json: any): CreateNonCustomAppointmentRequest {
    return CreateNonCustomAppointmentRequestToJSONTyped(json, false);
}

export function CreateNonCustomAppointmentRequestToJSONTyped(value?: CreateNonCustomAppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDatetimeEnterpriseServiceLocal': value['startDatetimeEnterpriseServiceLocal'],
        'endDatetimeEnterpriseServiceLocal': value['endDatetimeEnterpriseServiceLocal'],
    };
}

