/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeWindow } from './TimeWindow';
import {
    TimeWindowFromJSON,
    TimeWindowFromJSONTyped,
    TimeWindowToJSON,
    TimeWindowToJSONTyped,
} from './TimeWindow';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface CreateCustomAppointmentsEnterpriseServiceRequest
 */
export interface CreateCustomAppointmentsEnterpriseServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    description: string;
    /**
     * 
     * @type {Location}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    location: Location;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    timeZone: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    maxDistanceKm: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    cathegory: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    price: number;
    /**
     * currency ISO code
     * @type {string}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    currency: string;
    /**
     * 
     * @type {Array<TimeWindow>}
     * @memberof CreateCustomAppointmentsEnterpriseServiceRequest
     */
    timeWindows: Array<TimeWindow>;
}

/**
 * Check if a given object implements the CreateCustomAppointmentsEnterpriseServiceRequest interface.
 */
export function instanceOfCreateCustomAppointmentsEnterpriseServiceRequest(value: object): value is CreateCustomAppointmentsEnterpriseServiceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('timeZone' in value) || value['timeZone'] === undefined) return false;
    if (!('maxDistanceKm' in value) || value['maxDistanceKm'] === undefined) return false;
    if (!('cathegory' in value) || value['cathegory'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('timeWindows' in value) || value['timeWindows'] === undefined) return false;
    return true;
}

export function CreateCustomAppointmentsEnterpriseServiceRequestFromJSON(json: any): CreateCustomAppointmentsEnterpriseServiceRequest {
    return CreateCustomAppointmentsEnterpriseServiceRequestFromJSONTyped(json, false);
}

export function CreateCustomAppointmentsEnterpriseServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomAppointmentsEnterpriseServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'location': LocationFromJSON(json['location']),
        'timeZone': json['timeZone'],
        'maxDistanceKm': json['maxDistanceKm'],
        'cathegory': json['cathegory'],
        'price': json['price'],
        'currency': json['currency'],
        'timeWindows': ((json['timeWindows'] as Array<any>).map(TimeWindowFromJSON)),
    };
}

export function CreateCustomAppointmentsEnterpriseServiceRequestToJSON(json: any): CreateCustomAppointmentsEnterpriseServiceRequest {
    return CreateCustomAppointmentsEnterpriseServiceRequestToJSONTyped(json, false);
}

export function CreateCustomAppointmentsEnterpriseServiceRequestToJSONTyped(value?: CreateCustomAppointmentsEnterpriseServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timeZone': value['timeZone'],
        'maxDistanceKm': value['maxDistanceKm'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currency': value['currency'],
        'timeWindows': ((value['timeWindows'] as Array<any>).map(TimeWindowToJSON)),
    };
}

