/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseRequest
 */
export interface CreateEnterpriseRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    logoFileName?: string;
    /**
     * 
     * @type {Blob}
     * @memberof CreateEnterpriseRequest
     */
    logoFile?: Blob;
    /**
     * 
     * @type {string}
     * @memberof CreateEnterpriseRequest
     */
    backgroundPhotoFileName?: string;
    /**
     * 
     * @type {Blob}
     * @memberof CreateEnterpriseRequest
     */
    backgroundPhotoFile?: Blob;
}

/**
 * Check if a given object implements the CreateEnterpriseRequest interface.
 */
export function instanceOfCreateEnterpriseRequest(value: object): value is CreateEnterpriseRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function CreateEnterpriseRequestFromJSON(json: any): CreateEnterpriseRequest {
    return CreateEnterpriseRequestFromJSONTyped(json, false);
}

export function CreateEnterpriseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'location': json['location'],
        'logoFileName': json['logoFileName'] == null ? undefined : json['logoFileName'],
        'logoFile': json['logoFile'] == null ? undefined : json['logoFile'],
        'backgroundPhotoFileName': json['backgroundPhotoFileName'] == null ? undefined : json['backgroundPhotoFileName'],
        'backgroundPhotoFile': json['backgroundPhotoFile'] == null ? undefined : json['backgroundPhotoFile'],
    };
}

export function CreateEnterpriseRequestToJSON(json: any): CreateEnterpriseRequest {
    return CreateEnterpriseRequestToJSONTyped(json, false);
}

export function CreateEnterpriseRequestToJSONTyped(value?: CreateEnterpriseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'logoFileName': value['logoFileName'],
        'logoFile': value['logoFile'],
        'backgroundPhotoFileName': value['backgroundPhotoFileName'],
        'backgroundPhotoFile': value['backgroundPhotoFile'],
    };
}

