/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdyenSessionResponse
 */
export interface CreateAdyenSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAdyenSessionResponse
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the CreateAdyenSessionResponse interface.
 */
export function instanceOfCreateAdyenSessionResponse(value: object): value is CreateAdyenSessionResponse {
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    return true;
}

export function CreateAdyenSessionResponseFromJSON(json: any): CreateAdyenSessionResponse {
    return CreateAdyenSessionResponseFromJSONTyped(json, false);
}

export function CreateAdyenSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdyenSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirectUrl'],
    };
}

export function CreateAdyenSessionResponseToJSON(json: any): CreateAdyenSessionResponse {
    return CreateAdyenSessionResponseToJSONTyped(json, false);
}

export function CreateAdyenSessionResponseToJSONTyped(value?: CreateAdyenSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirectUrl': value['redirectUrl'],
    };
}

