/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEnterpriseResponse
 */
export interface CreateEnterpriseResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateEnterpriseResponse
     */
    enterpriseId: number;
}

/**
 * Check if a given object implements the CreateEnterpriseResponse interface.
 */
export function instanceOfCreateEnterpriseResponse(value: object): value is CreateEnterpriseResponse {
    if (!('enterpriseId' in value) || value['enterpriseId'] === undefined) return false;
    return true;
}

export function CreateEnterpriseResponseFromJSON(json: any): CreateEnterpriseResponse {
    return CreateEnterpriseResponseFromJSONTyped(json, false);
}

export function CreateEnterpriseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnterpriseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseId': json['enterpriseId'],
    };
}

export function CreateEnterpriseResponseToJSON(json: any): CreateEnterpriseResponse {
    return CreateEnterpriseResponseToJSONTyped(json, false);
}

export function CreateEnterpriseResponseToJSONTyped(value?: CreateEnterpriseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseId': value['enterpriseId'],
    };
}

