/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface CreateCustomAppointmentRequest
 */
export interface CreateCustomAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentRequest
     */
    startDatetimeShopLocal?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomAppointmentRequest
     */
    endDatetimeShopLocal?: string;
    /**
     * 
     * @type {Location}
     * @memberof CreateCustomAppointmentRequest
     */
    location?: Location;
}

/**
 * Check if a given object implements the CreateCustomAppointmentRequest interface.
 */
export function instanceOfCreateCustomAppointmentRequest(value: object): value is CreateCustomAppointmentRequest {
    return true;
}

export function CreateCustomAppointmentRequestFromJSON(json: any): CreateCustomAppointmentRequest {
    return CreateCustomAppointmentRequestFromJSONTyped(json, false);
}

export function CreateCustomAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomAppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDatetimeShopLocal': json['startDatetimeShopLocal'] == null ? undefined : json['startDatetimeShopLocal'],
        'endDatetimeShopLocal': json['endDatetimeShopLocal'] == null ? undefined : json['endDatetimeShopLocal'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
    };
}

export function CreateCustomAppointmentRequestToJSON(json: any): CreateCustomAppointmentRequest {
    return CreateCustomAppointmentRequestToJSONTyped(json, false);
}

export function CreateCustomAppointmentRequestToJSONTyped(value?: CreateCustomAppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDatetimeShopLocal': value['startDatetimeShopLocal'],
        'endDatetimeShopLocal': value['endDatetimeShopLocal'],
        'location': LocationToJSON(value['location']),
    };
}

