/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdyenAmount } from './AdyenAmount';
import {
    AdyenAmountFromJSON,
    AdyenAmountFromJSONTyped,
    AdyenAmountToJSON,
    AdyenAmountToJSONTyped,
} from './AdyenAmount';
import type { AdyenPaymentMethod } from './AdyenPaymentMethod';
import {
    AdyenPaymentMethodFromJSON,
    AdyenPaymentMethodFromJSONTyped,
    AdyenPaymentMethodToJSON,
    AdyenPaymentMethodToJSONTyped,
} from './AdyenPaymentMethod';

/**
 * 
 * @export
 * @interface CreateAdyenSessionResponsePayment
 */
export interface CreateAdyenSessionResponsePayment {
    /**
     * 
     * @type {AdyenAmount}
     * @memberof CreateAdyenSessionResponsePayment
     */
    amount: AdyenAmount;
    /**
     * 
     * @type {AdyenPaymentMethod}
     * @memberof CreateAdyenSessionResponsePayment
     */
    paymentMethod: AdyenPaymentMethod;
    /**
     * 
     * @type {string}
     * @memberof CreateAdyenSessionResponsePayment
     */
    pspReference: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdyenSessionResponsePayment
     */
    resultCode: string;
}

/**
 * Check if a given object implements the CreateAdyenSessionResponsePayment interface.
 */
export function instanceOfCreateAdyenSessionResponsePayment(value: object): value is CreateAdyenSessionResponsePayment {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('pspReference' in value) || value['pspReference'] === undefined) return false;
    if (!('resultCode' in value) || value['resultCode'] === undefined) return false;
    return true;
}

export function CreateAdyenSessionResponsePaymentFromJSON(json: any): CreateAdyenSessionResponsePayment {
    return CreateAdyenSessionResponsePaymentFromJSONTyped(json, false);
}

export function CreateAdyenSessionResponsePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdyenSessionResponsePayment {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': AdyenAmountFromJSON(json['amount']),
        'paymentMethod': AdyenPaymentMethodFromJSON(json['paymentMethod']),
        'pspReference': json['pspReference'],
        'resultCode': json['resultCode'],
    };
}

export function CreateAdyenSessionResponsePaymentToJSON(json: any): CreateAdyenSessionResponsePayment {
    return CreateAdyenSessionResponsePaymentToJSONTyped(json, false);
}

export function CreateAdyenSessionResponsePaymentToJSONTyped(value?: CreateAdyenSessionResponsePayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': AdyenAmountToJSON(value['amount']),
        'paymentMethod': AdyenPaymentMethodToJSON(value['paymentMethod']),
        'pspReference': value['pspReference'],
        'resultCode': value['resultCode'],
    };
}

