/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeGetMeResponse
 */
export interface EmployeeGetMeResponse {
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetMeResponse
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeGetMeResponse
     */
    enterpriseId: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetMeResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetMeResponse
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeGetMeResponse
     */
    lastName: string;
}

/**
 * Check if a given object implements the EmployeeGetMeResponse interface.
 */
export function instanceOfEmployeeGetMeResponse(value: object): value is EmployeeGetMeResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('enterpriseId' in value) || value['enterpriseId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function EmployeeGetMeResponseFromJSON(json: any): EmployeeGetMeResponse {
    return EmployeeGetMeResponseFromJSONTyped(json, false);
}

export function EmployeeGetMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeGetMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'enterpriseId': json['enterpriseId'],
        'username': json['username'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function EmployeeGetMeResponseToJSON(json: any): EmployeeGetMeResponse {
    return EmployeeGetMeResponseToJSONTyped(json, false);
}

export function EmployeeGetMeResponseToJSONTyped(value?: EmployeeGetMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'enterpriseId': value['enterpriseId'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

