/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntrepreneurGetMeResponse
 */
export interface EntrepreneurGetMeResponse {
    /**
     * 
     * @type {number}
     * @memberof EntrepreneurGetMeResponse
     */
    independentEndUserId: number;
    /**
     * 
     * @type {number}
     * @memberof EntrepreneurGetMeResponse
     */
    entrepreneurId: number;
    /**
     * 
     * @type {string}
     * @memberof EntrepreneurGetMeResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EntrepreneurGetMeResponse
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof EntrepreneurGetMeResponse
     */
    lastName: string;
}

/**
 * Check if a given object implements the EntrepreneurGetMeResponse interface.
 */
export function instanceOfEntrepreneurGetMeResponse(value: object): value is EntrepreneurGetMeResponse {
    if (!('independentEndUserId' in value) || value['independentEndUserId'] === undefined) return false;
    if (!('entrepreneurId' in value) || value['entrepreneurId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function EntrepreneurGetMeResponseFromJSON(json: any): EntrepreneurGetMeResponse {
    return EntrepreneurGetMeResponseFromJSONTyped(json, false);
}

export function EntrepreneurGetMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntrepreneurGetMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'independentEndUserId': json['independentEndUserId'],
        'entrepreneurId': json['entrepreneurId'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function EntrepreneurGetMeResponseToJSON(json: any): EntrepreneurGetMeResponse {
    return EntrepreneurGetMeResponseToJSONTyped(json, false);
}

export function EntrepreneurGetMeResponseToJSONTyped(value?: EntrepreneurGetMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'independentEndUserId': value['independentEndUserId'],
        'entrepreneurId': value['entrepreneurId'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

