/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCustomerLandingPagePendingAppointmentResponseItem
 */
export interface GetCustomerLandingPagePendingAppointmentResponseItem {
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    serviceName: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    startDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    endDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    timezone: string;
    /**
     * 
     * @type {number}
     * @memberof GetCustomerLandingPagePendingAppointmentResponseItem
     */
    price: number;
}

/**
 * Check if a given object implements the GetCustomerLandingPagePendingAppointmentResponseItem interface.
 */
export function instanceOfGetCustomerLandingPagePendingAppointmentResponseItem(value: object): value is GetCustomerLandingPagePendingAppointmentResponseItem {
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('startDatetimeServiceLocal' in value) || value['startDatetimeServiceLocal'] === undefined) return false;
    if (!('endDatetimeServiceLocal' in value) || value['endDatetimeServiceLocal'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function GetCustomerLandingPagePendingAppointmentResponseItemFromJSON(json: any): GetCustomerLandingPagePendingAppointmentResponseItem {
    return GetCustomerLandingPagePendingAppointmentResponseItemFromJSONTyped(json, false);
}

export function GetCustomerLandingPagePendingAppointmentResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCustomerLandingPagePendingAppointmentResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'enterpriseName': json['enterpriseName'],
        'address': json['address'],
        'startDatetimeServiceLocal': json['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': json['endDatetimeServiceLocal'],
        'timezone': json['timezone'],
        'price': json['price'],
    };
}

export function GetCustomerLandingPagePendingAppointmentResponseItemToJSON(json: any): GetCustomerLandingPagePendingAppointmentResponseItem {
    return GetCustomerLandingPagePendingAppointmentResponseItemToJSONTyped(json, false);
}

export function GetCustomerLandingPagePendingAppointmentResponseItemToJSONTyped(value?: GetCustomerLandingPagePendingAppointmentResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'enterpriseName': value['enterpriseName'],
        'address': value['address'],
        'startDatetimeServiceLocal': value['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': value['endDatetimeServiceLocal'],
        'timezone': value['timezone'],
        'price': value['price'],
    };
}

