/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCustomerLandingPageScheduledAppointmentResponse
 */
export interface GetCustomerLandingPageScheduledAppointmentResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    serviceName: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    address: string;
    /**
     * 
     * @type {Date}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    startDatetimeGlobal: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    endDatetimeGlobal: Date;
    /**
     * 
     * @type {number}
     * @memberof GetCustomerLandingPageScheduledAppointmentResponse
     */
    price: number;
}

/**
 * Check if a given object implements the GetCustomerLandingPageScheduledAppointmentResponse interface.
 */
export function instanceOfGetCustomerLandingPageScheduledAppointmentResponse(value: object): value is GetCustomerLandingPageScheduledAppointmentResponse {
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('startDatetimeGlobal' in value) || value['startDatetimeGlobal'] === undefined) return false;
    if (!('endDatetimeGlobal' in value) || value['endDatetimeGlobal'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function GetCustomerLandingPageScheduledAppointmentResponseFromJSON(json: any): GetCustomerLandingPageScheduledAppointmentResponse {
    return GetCustomerLandingPageScheduledAppointmentResponseFromJSONTyped(json, false);
}

export function GetCustomerLandingPageScheduledAppointmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCustomerLandingPageScheduledAppointmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'enterpriseName': json['enterpriseName'],
        'address': json['address'],
        'startDatetimeGlobal': (new Date(json['startDatetimeGlobal'])),
        'endDatetimeGlobal': (new Date(json['endDatetimeGlobal'])),
        'price': json['price'],
    };
}

export function GetCustomerLandingPageScheduledAppointmentResponseToJSON(json: any): GetCustomerLandingPageScheduledAppointmentResponse {
    return GetCustomerLandingPageScheduledAppointmentResponseToJSONTyped(json, false);
}

export function GetCustomerLandingPageScheduledAppointmentResponseToJSONTyped(value?: GetCustomerLandingPageScheduledAppointmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'enterpriseName': value['enterpriseName'],
        'address': value['address'],
        'startDatetimeGlobal': ((value['startDatetimeGlobal']).toISOString()),
        'endDatetimeGlobal': ((value['endDatetimeGlobal']).toISOString()),
        'price': value['price'],
    };
}

