/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseRequest
 */
export interface GetEnterpriseRequest {
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseRequest
     */
    enterpriseId?: number;
}

/**
 * Check if a given object implements the GetEnterpriseRequest interface.
 */
export function instanceOfGetEnterpriseRequest(value: object): value is GetEnterpriseRequest {
    return true;
}

export function GetEnterpriseRequestFromJSON(json: any): GetEnterpriseRequest {
    return GetEnterpriseRequestFromJSONTyped(json, false);
}

export function GetEnterpriseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseId': json['enterpriseId'] == null ? undefined : json['enterpriseId'],
    };
}

export function GetEnterpriseRequestToJSON(json: any): GetEnterpriseRequest {
    return GetEnterpriseRequestToJSONTyped(json, false);
}

export function GetEnterpriseRequestToJSONTyped(value?: GetEnterpriseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseId': value['enterpriseId'],
    };
}

