/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface GetEnterpriseServiceCustomServiceResponse
 */
export interface GetEnterpriseServiceCustomServiceResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    readonly takesCustomAppointments: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    serviceId: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    description: string;
    /**
     * 
     * @type {Location}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    location: Location;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    timezone: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    maxDistanceKm: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    cathegory: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceCustomServiceResponse
     */
    currencyIso: string;
}

/**
 * Check if a given object implements the GetEnterpriseServiceCustomServiceResponse interface.
 */
export function instanceOfGetEnterpriseServiceCustomServiceResponse(value: object): value is GetEnterpriseServiceCustomServiceResponse {
    if (!('takesCustomAppointments' in value) || value['takesCustomAppointments'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('maxDistanceKm' in value) || value['maxDistanceKm'] === undefined) return false;
    if (!('cathegory' in value) || value['cathegory'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currencyIso' in value) || value['currencyIso'] === undefined) return false;
    return true;
}

export function GetEnterpriseServiceCustomServiceResponseFromJSON(json: any): GetEnterpriseServiceCustomServiceResponse {
    return GetEnterpriseServiceCustomServiceResponseFromJSONTyped(json, false);
}

export function GetEnterpriseServiceCustomServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServiceCustomServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'takesCustomAppointments': json['takesCustomAppointments'],
        'serviceId': json['serviceId'],
        'name': json['name'],
        'description': json['description'],
        'location': LocationFromJSON(json['location']),
        'timezone': json['timezone'],
        'maxDistanceKm': json['maxDistanceKm'],
        'cathegory': json['cathegory'],
        'price': json['price'],
        'currencyIso': json['currencyIso'],
    };
}

export function GetEnterpriseServiceCustomServiceResponseToJSON(json: any): GetEnterpriseServiceCustomServiceResponse {
    return GetEnterpriseServiceCustomServiceResponseToJSONTyped(json, false);
}

export function GetEnterpriseServiceCustomServiceResponseToJSONTyped(value?: Omit<GetEnterpriseServiceCustomServiceResponse, 'takesCustomAppointments'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timezone': value['timezone'],
        'maxDistanceKm': value['maxDistanceKm'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currencyIso': value['currencyIso'],
    };
}

