/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEntrepreneurEnterprisesResponseItem
 */
export interface GetEntrepreneurEnterprisesResponseItem {
    /**
     * 
     * @type {string}
     * @memberof GetEntrepreneurEnterprisesResponseItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetEntrepreneurEnterprisesResponseItem
     */
    id: number;
}

/**
 * Check if a given object implements the GetEntrepreneurEnterprisesResponseItem interface.
 */
export function instanceOfGetEntrepreneurEnterprisesResponseItem(value: object): value is GetEntrepreneurEnterprisesResponseItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetEntrepreneurEnterprisesResponseItemFromJSON(json: any): GetEntrepreneurEnterprisesResponseItem {
    return GetEntrepreneurEnterprisesResponseItemFromJSONTyped(json, false);
}

export function GetEntrepreneurEnterprisesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEntrepreneurEnterprisesResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function GetEntrepreneurEnterprisesResponseItemToJSON(json: any): GetEntrepreneurEnterprisesResponseItem {
    return GetEntrepreneurEnterprisesResponseItemToJSONTyped(json, false);
}

export function GetEntrepreneurEnterprisesResponseItemToJSONTyped(value?: GetEntrepreneurEnterprisesResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
    };
}

