/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseServicesResponseItem
 */
export interface GetEnterpriseServicesResponseItem {
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServicesResponseItem
     */
    serviceId?: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicesResponseItem
     */
    serviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicesResponseItem
     */
    serviceDescription?: string;
}

/**
 * Check if a given object implements the GetEnterpriseServicesResponseItem interface.
 */
export function instanceOfGetEnterpriseServicesResponseItem(value: object): value is GetEnterpriseServicesResponseItem {
    return true;
}

export function GetEnterpriseServicesResponseItemFromJSON(json: any): GetEnterpriseServicesResponseItem {
    return GetEnterpriseServicesResponseItemFromJSONTyped(json, false);
}

export function GetEnterpriseServicesResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServicesResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'] == null ? undefined : json['serviceId'],
        'serviceName': json['serviceName'] == null ? undefined : json['serviceName'],
        'serviceDescription': json['serviceDescription'] == null ? undefined : json['serviceDescription'],
    };
}

export function GetEnterpriseServicesResponseItemToJSON(json: any): GetEnterpriseServicesResponseItem {
    return GetEnterpriseServicesResponseItemToJSONTyped(json, false);
}

export function GetEnterpriseServicesResponseItemToJSONTyped(value?: GetEnterpriseServicesResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'serviceName': value['serviceName'],
        'serviceDescription': value['serviceDescription'],
    };
}

