/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseServiceReviewResponse
 */
export interface GetEnterpriseServiceReviewResponse {
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceReviewResponse
     */
    numStarsOutOf5: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceReviewResponse
     */
    text: string;
}

/**
 * Check if a given object implements the GetEnterpriseServiceReviewResponse interface.
 */
export function instanceOfGetEnterpriseServiceReviewResponse(value: object): value is GetEnterpriseServiceReviewResponse {
    if (!('numStarsOutOf5' in value) || value['numStarsOutOf5'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function GetEnterpriseServiceReviewResponseFromJSON(json: any): GetEnterpriseServiceReviewResponse {
    return GetEnterpriseServiceReviewResponseFromJSONTyped(json, false);
}

export function GetEnterpriseServiceReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServiceReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'numStarsOutOf5': json['numStarsOutOf5'],
        'text': json['text'],
    };
}

export function GetEnterpriseServiceReviewResponseToJSON(json: any): GetEnterpriseServiceReviewResponse {
    return GetEnterpriseServiceReviewResponseToJSONTyped(json, false);
}

export function GetEnterpriseServiceReviewResponseToJSONTyped(value?: GetEnterpriseServiceReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numStarsOutOf5': value['numStarsOutOf5'],
        'text': value['text'],
    };
}

