/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseResponse
 */
export interface GetEnterpriseResponse {
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseResponse
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseResponse
     */
    location: string;
}

/**
 * Check if a given object implements the GetEnterpriseResponse interface.
 */
export function instanceOfGetEnterpriseResponse(value: object): value is GetEnterpriseResponse {
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function GetEnterpriseResponseFromJSON(json: any): GetEnterpriseResponse {
    return GetEnterpriseResponseFromJSONTyped(json, false);
}

export function GetEnterpriseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseName': json['enterpriseName'],
        'description': json['description'],
        'location': json['location'],
    };
}

export function GetEnterpriseResponseToJSON(json: any): GetEnterpriseResponse {
    return GetEnterpriseResponseToJSONTyped(json, false);
}

export function GetEnterpriseResponseToJSONTyped(value?: GetEnterpriseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseName': value['enterpriseName'],
        'description': value['description'],
        'location': value['location'],
    };
}

