/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Slot } from './Slot';
import {
    SlotFromJSON,
    SlotFromJSONTyped,
    SlotToJSON,
    SlotToJSONTyped,
} from './Slot';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface GetEnterpriseServiceNonCustomServiceResponse
 */
export interface GetEnterpriseServiceNonCustomServiceResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    readonly takesCustomAppointments: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    enterpriseId: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    enterpriseName: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    serviceId: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    description: string;
    /**
     * 
     * @type {Location}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    location: Location;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    timezone: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    cathegory: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    currencyIso: string;
    /**
     * 
     * @type {Array<Slot>}
     * @memberof GetEnterpriseServiceNonCustomServiceResponse
     */
    slots: Array<Slot>;
}

/**
 * Check if a given object implements the GetEnterpriseServiceNonCustomServiceResponse interface.
 */
export function instanceOfGetEnterpriseServiceNonCustomServiceResponse(value: object): value is GetEnterpriseServiceNonCustomServiceResponse {
    if (!('takesCustomAppointments' in value) || value['takesCustomAppointments'] === undefined) return false;
    if (!('enterpriseId' in value) || value['enterpriseId'] === undefined) return false;
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('cathegory' in value) || value['cathegory'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currencyIso' in value) || value['currencyIso'] === undefined) return false;
    if (!('slots' in value) || value['slots'] === undefined) return false;
    return true;
}

export function GetEnterpriseServiceNonCustomServiceResponseFromJSON(json: any): GetEnterpriseServiceNonCustomServiceResponse {
    return GetEnterpriseServiceNonCustomServiceResponseFromJSONTyped(json, false);
}

export function GetEnterpriseServiceNonCustomServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServiceNonCustomServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'takesCustomAppointments': json['takesCustomAppointments'],
        'enterpriseId': json['enterpriseId'],
        'enterpriseName': json['enterpriseName'],
        'serviceId': json['serviceId'],
        'name': json['name'],
        'description': json['description'],
        'location': LocationFromJSON(json['location']),
        'timezone': json['timezone'],
        'cathegory': json['cathegory'],
        'price': json['price'],
        'currencyIso': json['currencyIso'],
        'slots': ((json['slots'] as Array<any>).map(SlotFromJSON)),
    };
}

export function GetEnterpriseServiceNonCustomServiceResponseToJSON(json: any): GetEnterpriseServiceNonCustomServiceResponse {
    return GetEnterpriseServiceNonCustomServiceResponseToJSONTyped(json, false);
}

export function GetEnterpriseServiceNonCustomServiceResponseToJSONTyped(value?: Omit<GetEnterpriseServiceNonCustomServiceResponse, 'takesCustomAppointments'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseId': value['enterpriseId'],
        'enterpriseName': value['enterpriseName'],
        'serviceId': value['serviceId'],
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timezone': value['timezone'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currencyIso': value['currencyIso'],
        'slots': ((value['slots'] as Array<any>).map(SlotToJSON)),
    };
}

