/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseServiceFutureAppointmentsResponse
 */
export interface GetEnterpriseServiceFutureAppointmentsResponse {
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    userFirstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    userLastName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    startDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    endDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    timezone: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServiceFutureAppointmentsResponse
     */
    currency: string;
}

/**
 * Check if a given object implements the GetEnterpriseServiceFutureAppointmentsResponse interface.
 */
export function instanceOfGetEnterpriseServiceFutureAppointmentsResponse(value: object): value is GetEnterpriseServiceFutureAppointmentsResponse {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('userFirstName' in value) || value['userFirstName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('startDatetimeServiceLocal' in value) || value['startDatetimeServiceLocal'] === undefined) return false;
    if (!('endDatetimeServiceLocal' in value) || value['endDatetimeServiceLocal'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function GetEnterpriseServiceFutureAppointmentsResponseFromJSON(json: any): GetEnterpriseServiceFutureAppointmentsResponse {
    return GetEnterpriseServiceFutureAppointmentsResponseFromJSONTyped(json, false);
}

export function GetEnterpriseServiceFutureAppointmentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServiceFutureAppointmentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'userFirstName': json['userFirstName'],
        'userLastName': json['UserLastName'] == null ? undefined : json['UserLastName'],
        'address': json['address'],
        'startDatetimeServiceLocal': json['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': json['endDatetimeServiceLocal'],
        'timezone': json['timezone'],
        'price': json['price'],
        'currency': json['currency'],
    };
}

export function GetEnterpriseServiceFutureAppointmentsResponseToJSON(json: any): GetEnterpriseServiceFutureAppointmentsResponse {
    return GetEnterpriseServiceFutureAppointmentsResponseToJSONTyped(json, false);
}

export function GetEnterpriseServiceFutureAppointmentsResponseToJSONTyped(value?: GetEnterpriseServiceFutureAppointmentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'userFirstName': value['userFirstName'],
        'UserLastName': value['userLastName'],
        'address': value['address'],
        'startDatetimeServiceLocal': value['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': value['endDatetimeServiceLocal'],
        'timezone': value['timezone'],
        'price': value['price'],
        'currency': value['currency'],
    };
}

