/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseEmployeesRequest
 */
export interface GetEnterpriseEmployeesRequest {
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseEmployeesRequest
     */
    enterpriseID?: number;
}

/**
 * Check if a given object implements the GetEnterpriseEmployeesRequest interface.
 */
export function instanceOfGetEnterpriseEmployeesRequest(value: object): value is GetEnterpriseEmployeesRequest {
    return true;
}

export function GetEnterpriseEmployeesRequestFromJSON(json: any): GetEnterpriseEmployeesRequest {
    return GetEnterpriseEmployeesRequestFromJSONTyped(json, false);
}

export function GetEnterpriseEmployeesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseEmployeesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseID': json['enterpriseID'] == null ? undefined : json['enterpriseID'],
    };
}

export function GetEnterpriseEmployeesRequestToJSON(json: any): GetEnterpriseEmployeesRequest {
    return GetEnterpriseEmployeesRequestToJSONTyped(json, false);
}

export function GetEnterpriseEmployeesRequestToJSONTyped(value?: GetEnterpriseEmployeesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseID': value['enterpriseID'],
    };
}

