/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEnterpriseServicePendingAppointmentResponse
 */
export interface GetEnterpriseServicePendingAppointmentResponse {
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    appointmentId: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    userFirstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    userLastName: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    startDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    endDatetimeServiceLocal: string;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    timezone: string;
    /**
     * 
     * @type {number}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof GetEnterpriseServicePendingAppointmentResponse
     */
    currency: string;
}

/**
 * Check if a given object implements the GetEnterpriseServicePendingAppointmentResponse interface.
 */
export function instanceOfGetEnterpriseServicePendingAppointmentResponse(value: object): value is GetEnterpriseServicePendingAppointmentResponse {
    if (!('appointmentId' in value) || value['appointmentId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('userFirstName' in value) || value['userFirstName'] === undefined) return false;
    if (!('userLastName' in value) || value['userLastName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('startDatetimeServiceLocal' in value) || value['startDatetimeServiceLocal'] === undefined) return false;
    if (!('endDatetimeServiceLocal' in value) || value['endDatetimeServiceLocal'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function GetEnterpriseServicePendingAppointmentResponseFromJSON(json: any): GetEnterpriseServicePendingAppointmentResponse {
    return GetEnterpriseServicePendingAppointmentResponseFromJSONTyped(json, false);
}

export function GetEnterpriseServicePendingAppointmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnterpriseServicePendingAppointmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appointmentId': json['appointmentId'],
        'username': json['username'],
        'userFirstName': json['userFirstName'],
        'userLastName': json['userLastName'],
        'address': json['address'],
        'startDatetimeServiceLocal': json['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': json['endDatetimeServiceLocal'],
        'timezone': json['timezone'],
        'price': json['price'],
        'currency': json['currency'],
    };
}

export function GetEnterpriseServicePendingAppointmentResponseToJSON(json: any): GetEnterpriseServicePendingAppointmentResponse {
    return GetEnterpriseServicePendingAppointmentResponseToJSONTyped(json, false);
}

export function GetEnterpriseServicePendingAppointmentResponseToJSONTyped(value?: GetEnterpriseServicePendingAppointmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appointmentId': value['appointmentId'],
        'username': value['username'],
        'userFirstName': value['userFirstName'],
        'userLastName': value['userLastName'],
        'address': value['address'],
        'startDatetimeServiceLocal': value['startDatetimeServiceLocal'],
        'endDatetimeServiceLocal': value['endDatetimeServiceLocal'],
        'timezone': value['timezone'],
        'price': value['price'],
        'currency': value['currency'],
    };
}

