/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMyUserGroup200Response
 */
export interface GetMyUserGroup200Response {
    /**
     * 
     * @type {string}
     * @memberof GetMyUserGroup200Response
     */
    userGroup: string;
}

/**
 * Check if a given object implements the GetMyUserGroup200Response interface.
 */
export function instanceOfGetMyUserGroup200Response(value: object): value is GetMyUserGroup200Response {
    if (!('userGroup' in value) || value['userGroup'] === undefined) return false;
    return true;
}

export function GetMyUserGroup200ResponseFromJSON(json: any): GetMyUserGroup200Response {
    return GetMyUserGroup200ResponseFromJSONTyped(json, false);
}

export function GetMyUserGroup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyUserGroup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userGroup': json['userGroup'],
    };
}

export function GetMyUserGroup200ResponseToJSON(json: any): GetMyUserGroup200Response {
    return GetMyUserGroup200ResponseToJSONTyped(json, false);
}

export function GetMyUserGroup200ResponseToJSONTyped(value?: GetMyUserGroup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userGroup': value['userGroup'],
    };
}

