/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMeResponseEnterpreneur
 */
export interface GetMeResponseEnterpreneur {
    /**
     * 
     * @type {string}
     * @memberof GetMeResponseEnterpreneur
     */
    role: GetMeResponseEnterpreneurRoleEnum;
    /**
     * 
     * @type {number}
     * @memberof GetMeResponseEnterpreneur
     */
    entrepreneurId: number;
}


/**
 * @export
 */
export const GetMeResponseEnterpreneurRoleEnum = {
    Entrepreneur: 'ENTREPRENEUR'
} as const;
export type GetMeResponseEnterpreneurRoleEnum = typeof GetMeResponseEnterpreneurRoleEnum[keyof typeof GetMeResponseEnterpreneurRoleEnum];


/**
 * Check if a given object implements the GetMeResponseEnterpreneur interface.
 */
export function instanceOfGetMeResponseEnterpreneur(value: object): value is GetMeResponseEnterpreneur {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('entrepreneurId' in value) || value['entrepreneurId'] === undefined) return false;
    return true;
}

export function GetMeResponseEnterpreneurFromJSON(json: any): GetMeResponseEnterpreneur {
    return GetMeResponseEnterpreneurFromJSONTyped(json, false);
}

export function GetMeResponseEnterpreneurFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMeResponseEnterpreneur {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'entrepreneurId': json['entrepreneurId'],
    };
}

export function GetMeResponseEnterpreneurToJSON(json: any): GetMeResponseEnterpreneur {
    return GetMeResponseEnterpreneurToJSONTyped(json, false);
}

export function GetMeResponseEnterpreneurToJSONTyped(value?: GetMeResponseEnterpreneur | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'entrepreneurId': value['entrepreneurId'],
    };
}

