/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRegularAdminResponse
 */
export interface GetRegularAdminResponse {
    /**
     * 
     * @type {number}
     * @memberof GetRegularAdminResponse
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof GetRegularAdminResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof GetRegularAdminResponse
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetRegularAdminResponse
     */
    lastName: string;
}

/**
 * Check if a given object implements the GetRegularAdminResponse interface.
 */
export function instanceOfGetRegularAdminResponse(value: object): value is GetRegularAdminResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function GetRegularAdminResponseFromJSON(json: any): GetRegularAdminResponse {
    return GetRegularAdminResponseFromJSONTyped(json, false);
}

export function GetRegularAdminResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRegularAdminResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'username': json['username'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function GetRegularAdminResponseToJSON(json: any): GetRegularAdminResponse {
    return GetRegularAdminResponseToJSONTyped(json, false);
}

export function GetRegularAdminResponseToJSONTyped(value?: GetRegularAdminResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

