/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServiceFreeCustomAppointmentsResponseItem
 */
export interface GetServiceFreeCustomAppointmentsResponseItem {
    /**
     * 
     * @type {Date}
     * @memberof GetServiceFreeCustomAppointmentsResponseItem
     */
    startDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetServiceFreeCustomAppointmentsResponseItem
     */
    endDatetime: Date;
}

/**
 * Check if a given object implements the GetServiceFreeCustomAppointmentsResponseItem interface.
 */
export function instanceOfGetServiceFreeCustomAppointmentsResponseItem(value: object): value is GetServiceFreeCustomAppointmentsResponseItem {
    if (!('startDatetime' in value) || value['startDatetime'] === undefined) return false;
    if (!('endDatetime' in value) || value['endDatetime'] === undefined) return false;
    return true;
}

export function GetServiceFreeCustomAppointmentsResponseItemFromJSON(json: any): GetServiceFreeCustomAppointmentsResponseItem {
    return GetServiceFreeCustomAppointmentsResponseItemFromJSONTyped(json, false);
}

export function GetServiceFreeCustomAppointmentsResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceFreeCustomAppointmentsResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'startDatetime': (new Date(json['startDatetime'])),
        'endDatetime': (new Date(json['endDatetime'])),
    };
}

export function GetServiceFreeCustomAppointmentsResponseItemToJSON(json: any): GetServiceFreeCustomAppointmentsResponseItem {
    return GetServiceFreeCustomAppointmentsResponseItemToJSONTyped(json, false);
}

export function GetServiceFreeCustomAppointmentsResponseItemToJSONTyped(value?: GetServiceFreeCustomAppointmentsResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDatetime': ((value['startDatetime']).toISOString()),
        'endDatetime': ((value['endDatetime']).toISOString()),
    };
}

