/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServiceCustomAppointmentsStatus200Response
 */
export interface GetServiceCustomAppointmentsStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetServiceCustomAppointmentsStatus200Response
     */
    areCustomAppointmentsEnabled: boolean;
}

/**
 * Check if a given object implements the GetServiceCustomAppointmentsStatus200Response interface.
 */
export function instanceOfGetServiceCustomAppointmentsStatus200Response(value: object): value is GetServiceCustomAppointmentsStatus200Response {
    if (!('areCustomAppointmentsEnabled' in value) || value['areCustomAppointmentsEnabled'] === undefined) return false;
    return true;
}

export function GetServiceCustomAppointmentsStatus200ResponseFromJSON(json: any): GetServiceCustomAppointmentsStatus200Response {
    return GetServiceCustomAppointmentsStatus200ResponseFromJSONTyped(json, false);
}

export function GetServiceCustomAppointmentsStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServiceCustomAppointmentsStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'areCustomAppointmentsEnabled': json['areCustomAppointmentsEnabled'],
    };
}

export function GetServiceCustomAppointmentsStatus200ResponseToJSON(json: any): GetServiceCustomAppointmentsStatus200Response {
    return GetServiceCustomAppointmentsStatus200ResponseToJSONTyped(json, false);
}

export function GetServiceCustomAppointmentsStatus200ResponseToJSONTyped(value?: GetServiceCustomAppointmentsStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areCustomAppointmentsEnabled': value['areCustomAppointmentsEnabled'],
    };
}

