/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUnresolvedEnterpriseServiceReportResponse
 */
export interface GetUnresolvedEnterpriseServiceReportResponse {
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    reportId: number;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    enterpriseServiceId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    enterpriseServiceName: string;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    reportingUserType: string;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    reportingUserId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseServiceReportResponse
     */
    reportingUserUsername: string;
}

/**
 * Check if a given object implements the GetUnresolvedEnterpriseServiceReportResponse interface.
 */
export function instanceOfGetUnresolvedEnterpriseServiceReportResponse(value: object): value is GetUnresolvedEnterpriseServiceReportResponse {
    if (!('reportId' in value) || value['reportId'] === undefined) return false;
    if (!('enterpriseServiceId' in value) || value['enterpriseServiceId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('enterpriseServiceName' in value) || value['enterpriseServiceName'] === undefined) return false;
    if (!('reportingUserType' in value) || value['reportingUserType'] === undefined) return false;
    if (!('reportingUserId' in value) || value['reportingUserId'] === undefined) return false;
    if (!('reportingUserUsername' in value) || value['reportingUserUsername'] === undefined) return false;
    return true;
}

export function GetUnresolvedEnterpriseServiceReportResponseFromJSON(json: any): GetUnresolvedEnterpriseServiceReportResponse {
    return GetUnresolvedEnterpriseServiceReportResponseFromJSONTyped(json, false);
}

export function GetUnresolvedEnterpriseServiceReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnresolvedEnterpriseServiceReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['reportId'],
        'enterpriseServiceId': json['enterpriseServiceId'],
        'content': json['content'],
        'enterpriseServiceName': json['enterpriseServiceName'],
        'reportingUserType': json['reportingUserType'],
        'reportingUserId': json['reportingUserId'],
        'reportingUserUsername': json['reportingUserUsername'],
    };
}

export function GetUnresolvedEnterpriseServiceReportResponseToJSON(json: any): GetUnresolvedEnterpriseServiceReportResponse {
    return GetUnresolvedEnterpriseServiceReportResponseToJSONTyped(json, false);
}

export function GetUnresolvedEnterpriseServiceReportResponseToJSONTyped(value?: GetUnresolvedEnterpriseServiceReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportId': value['reportId'],
        'enterpriseServiceId': value['enterpriseServiceId'],
        'content': value['content'],
        'enterpriseServiceName': value['enterpriseServiceName'],
        'reportingUserType': value['reportingUserType'],
        'reportingUserId': value['reportingUserId'],
        'reportingUserUsername': value['reportingUserUsername'],
    };
}

