/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUnresolvedEnterpriseReportResponse
 */
export interface GetUnresolvedEnterpriseReportResponse {
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    reportId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    reportSubjectType: GetUnresolvedEnterpriseReportResponseReportSubjectTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    enterpriseId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    reportingUserType: string;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    reportingUserId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedEnterpriseReportResponse
     */
    reportingUserUsername: string;
}


/**
 * @export
 */
export const GetUnresolvedEnterpriseReportResponseReportSubjectTypeEnum = {
    Enterprise: 'ENTERPRISE'
} as const;
export type GetUnresolvedEnterpriseReportResponseReportSubjectTypeEnum = typeof GetUnresolvedEnterpriseReportResponseReportSubjectTypeEnum[keyof typeof GetUnresolvedEnterpriseReportResponseReportSubjectTypeEnum];


/**
 * Check if a given object implements the GetUnresolvedEnterpriseReportResponse interface.
 */
export function instanceOfGetUnresolvedEnterpriseReportResponse(value: object): value is GetUnresolvedEnterpriseReportResponse {
    if (!('reportId' in value) || value['reportId'] === undefined) return false;
    if (!('reportSubjectType' in value) || value['reportSubjectType'] === undefined) return false;
    if (!('enterpriseId' in value) || value['enterpriseId'] === undefined) return false;
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('reportingUserType' in value) || value['reportingUserType'] === undefined) return false;
    if (!('reportingUserId' in value) || value['reportingUserId'] === undefined) return false;
    if (!('reportingUserUsername' in value) || value['reportingUserUsername'] === undefined) return false;
    return true;
}

export function GetUnresolvedEnterpriseReportResponseFromJSON(json: any): GetUnresolvedEnterpriseReportResponse {
    return GetUnresolvedEnterpriseReportResponseFromJSONTyped(json, false);
}

export function GetUnresolvedEnterpriseReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnresolvedEnterpriseReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reportId': json['reportId'],
        'reportSubjectType': json['reportSubjectType'],
        'enterpriseId': json['enterpriseId'],
        'enterpriseName': json['enterpriseName'],
        'reportingUserType': json['reportingUserType'],
        'reportingUserId': json['reportingUserId'],
        'reportingUserUsername': json['reportingUserUsername'],
    };
}

export function GetUnresolvedEnterpriseReportResponseToJSON(json: any): GetUnresolvedEnterpriseReportResponse {
    return GetUnresolvedEnterpriseReportResponseToJSONTyped(json, false);
}

export function GetUnresolvedEnterpriseReportResponseToJSONTyped(value?: GetUnresolvedEnterpriseReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reportId': value['reportId'],
        'reportSubjectType': value['reportSubjectType'],
        'enterpriseId': value['enterpriseId'],
        'enterpriseName': value['enterpriseName'],
        'reportingUserType': value['reportingUserType'],
        'reportingUserId': value['reportingUserId'],
        'reportingUserUsername': value['reportingUserUsername'],
    };
}

