/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUnresolvedReportResponse
 */
export interface GetUnresolvedReportResponse {
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedReportResponse
     */
    creatorUserType: string;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedReportResponse
     */
    creatorUserId: number;
    /**
     * 
     * @type {string}
     * @memberof GetUnresolvedReportResponse
     */
    reportSubjectType: string;
    /**
     * 
     * @type {number}
     * @memberof GetUnresolvedReportResponse
     */
    reportSubjectId: number;
}

/**
 * Check if a given object implements the GetUnresolvedReportResponse interface.
 */
export function instanceOfGetUnresolvedReportResponse(value: object): value is GetUnresolvedReportResponse {
    if (!('creatorUserType' in value) || value['creatorUserType'] === undefined) return false;
    if (!('creatorUserId' in value) || value['creatorUserId'] === undefined) return false;
    if (!('reportSubjectType' in value) || value['reportSubjectType'] === undefined) return false;
    if (!('reportSubjectId' in value) || value['reportSubjectId'] === undefined) return false;
    return true;
}

export function GetUnresolvedReportResponseFromJSON(json: any): GetUnresolvedReportResponse {
    return GetUnresolvedReportResponseFromJSONTyped(json, false);
}

export function GetUnresolvedReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnresolvedReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorUserType': json['creatorUserType'],
        'creatorUserId': json['creatorUserId'],
        'reportSubjectType': json['reportSubjectType'],
        'reportSubjectId': json['reportSubjectId'],
    };
}

export function GetUnresolvedReportResponseToJSON(json: any): GetUnresolvedReportResponse {
    return GetUnresolvedReportResponseToJSONTyped(json, false);
}

export function GetUnresolvedReportResponseToJSONTyped(value?: GetUnresolvedReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creatorUserType': value['creatorUserType'],
        'creatorUserId': value['creatorUserId'],
        'reportSubjectType': value['reportSubjectType'],
        'reportSubjectId': value['reportSubjectId'],
    };
}

