/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetUnresolvedEnterpriseReportResponse } from './GetUnresolvedEnterpriseReportResponse';
import {
    instanceOfGetUnresolvedEnterpriseReportResponse,
    GetUnresolvedEnterpriseReportResponseFromJSON,
    GetUnresolvedEnterpriseReportResponseFromJSONTyped,
    GetUnresolvedEnterpriseReportResponseToJSON,
} from './GetUnresolvedEnterpriseReportResponse';
import type { GetUnresolvedEnterpriseServiceReportResponse } from './GetUnresolvedEnterpriseServiceReportResponse';
import {
    instanceOfGetUnresolvedEnterpriseServiceReportResponse,
    GetUnresolvedEnterpriseServiceReportResponseFromJSON,
    GetUnresolvedEnterpriseServiceReportResponseFromJSONTyped,
    GetUnresolvedEnterpriseServiceReportResponseToJSON,
} from './GetUnresolvedEnterpriseServiceReportResponse';
import type { GetUnresolvedReviewReportResponse } from './GetUnresolvedReviewReportResponse';
import {
    instanceOfGetUnresolvedReviewReportResponse,
    GetUnresolvedReviewReportResponseFromJSON,
    GetUnresolvedReviewReportResponseFromJSONTyped,
    GetUnresolvedReviewReportResponseToJSON,
} from './GetUnresolvedReviewReportResponse';

/**
 * @type GetUnresolvedReports200ResponseInner
 * 
 * @export
 */
export type GetUnresolvedReports200ResponseInner = GetUnresolvedEnterpriseReportResponse | GetUnresolvedEnterpriseServiceReportResponse | GetUnresolvedReviewReportResponse;

export function GetUnresolvedReports200ResponseInnerFromJSON(json: any): GetUnresolvedReports200ResponseInner {
    return GetUnresolvedReports200ResponseInnerFromJSONTyped(json, false);
}

export function GetUnresolvedReports200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnresolvedReports200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGetUnresolvedEnterpriseReportResponse(json)) {
        return GetUnresolvedEnterpriseReportResponseFromJSONTyped(json, true);
    }
    if (instanceOfGetUnresolvedEnterpriseServiceReportResponse(json)) {
        return GetUnresolvedEnterpriseServiceReportResponseFromJSONTyped(json, true);
    }
    if (instanceOfGetUnresolvedReviewReportResponse(json)) {
        return GetUnresolvedReviewReportResponseFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetUnresolvedReports200ResponseInnerToJSON(json: any): any {
    return GetUnresolvedReports200ResponseInnerToJSONTyped(json, false);
}

export function GetUnresolvedReports200ResponseInnerToJSONTyped(value?: GetUnresolvedReports200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGetUnresolvedEnterpriseReportResponse(value)) {
        return GetUnresolvedEnterpriseReportResponseToJSON(value as GetUnresolvedEnterpriseReportResponse);
    }
    if (instanceOfGetUnresolvedEnterpriseServiceReportResponse(value)) {
        return GetUnresolvedEnterpriseServiceReportResponseToJSON(value as GetUnresolvedEnterpriseServiceReportResponse);
    }
    if (instanceOfGetUnresolvedReviewReportResponse(value)) {
        return GetUnresolvedReviewReportResponseToJSON(value as GetUnresolvedReviewReportResponse);
    }

    return {};
}

