/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndependentEndUserGetMeResponse
 */
export interface IndependentEndUserGetMeResponse {
    /**
     * 
     * @type {number}
     * @memberof IndependentEndUserGetMeResponse
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof IndependentEndUserGetMeResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IndependentEndUserGetMeResponse
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof IndependentEndUserGetMeResponse
     */
    lastName: string;
}

/**
 * Check if a given object implements the IndependentEndUserGetMeResponse interface.
 */
export function instanceOfIndependentEndUserGetMeResponse(value: object): value is IndependentEndUserGetMeResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function IndependentEndUserGetMeResponseFromJSON(json: any): IndependentEndUserGetMeResponse {
    return IndependentEndUserGetMeResponseFromJSONTyped(json, false);
}

export function IndependentEndUserGetMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndependentEndUserGetMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'email': json['email'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function IndependentEndUserGetMeResponseToJSON(json: any): IndependentEndUserGetMeResponse {
    return IndependentEndUserGetMeResponseToJSONTyped(json, false);
}

export function IndependentEndUserGetMeResponseToJSONTyped(value?: IndependentEndUserGetMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

