/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject5
 */
export interface InlineObject5 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject5
     */
    message: string;
}

/**
 * Check if a given object implements the InlineObject5 interface.
 */
export function instanceOfInlineObject5(value: object): value is InlineObject5 {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function InlineObject5FromJSON(json: any): InlineObject5 {
    return InlineObject5FromJSONTyped(json, false);
}

export function InlineObject5FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject5 {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function InlineObject5ToJSON(json: any): InlineObject5 {
    return InlineObject5ToJSONTyped(json, false);
}

export function InlineObject5ToJSONTyped(value?: InlineObject5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

