/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInAdminResponse
 */
export interface LogInAdminResponse {
    /**
     * 
     * @type {string}
     * @memberof LogInAdminResponse
     */
    accessToken: string;
}

/**
 * Check if a given object implements the LogInAdminResponse interface.
 */
export function instanceOfLogInAdminResponse(value: object): value is LogInAdminResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function LogInAdminResponseFromJSON(json: any): LogInAdminResponse {
    return LogInAdminResponseFromJSONTyped(json, false);
}

export function LogInAdminResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInAdminResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function LogInAdminResponseToJSON(json: any): LogInAdminResponse {
    return LogInAdminResponseToJSONTyped(json, false);
}

export function LogInAdminResponseToJSONTyped(value?: LogInAdminResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

