/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInAdminRequest
 */
export interface LogInAdminRequest {
    /**
     * 
     * @type {string}
     * @memberof LogInAdminRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LogInAdminRequest
     */
    password: string;
}

/**
 * Check if a given object implements the LogInAdminRequest interface.
 */
export function instanceOfLogInAdminRequest(value: object): value is LogInAdminRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LogInAdminRequestFromJSON(json: any): LogInAdminRequest {
    return LogInAdminRequestFromJSONTyped(json, false);
}

export function LogInAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LogInAdminRequestToJSON(json: any): LogInAdminRequest {
    return LogInAdminRequestToJSONTyped(json, false);
}

export function LogInAdminRequestToJSONTyped(value?: LogInAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

