/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInIndependentEndUserRequest
 */
export interface LogInIndependentEndUserRequest {
    /**
     * 
     * @type {string}
     * @memberof LogInIndependentEndUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LogInIndependentEndUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the LogInIndependentEndUserRequest interface.
 */
export function instanceOfLogInIndependentEndUserRequest(value: object): value is LogInIndependentEndUserRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LogInIndependentEndUserRequestFromJSON(json: any): LogInIndependentEndUserRequest {
    return LogInIndependentEndUserRequestFromJSONTyped(json, false);
}

export function LogInIndependentEndUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInIndependentEndUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LogInIndependentEndUserRequestToJSON(json: any): LogInIndependentEndUserRequest {
    return LogInIndependentEndUserRequestToJSONTyped(json, false);
}

export function LogInIndependentEndUserRequestToJSONTyped(value?: LogInIndependentEndUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

