/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInEnterpriseEmployeeRequest
 */
export interface LogInEnterpriseEmployeeRequest {
    /**
     * 
     * @type {number}
     * @memberof LogInEnterpriseEmployeeRequest
     */
    enterpriseId: number;
    /**
     * 
     * @type {string}
     * @memberof LogInEnterpriseEmployeeRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LogInEnterpriseEmployeeRequest
     */
    password: string;
}

/**
 * Check if a given object implements the LogInEnterpriseEmployeeRequest interface.
 */
export function instanceOfLogInEnterpriseEmployeeRequest(value: object): value is LogInEnterpriseEmployeeRequest {
    if (!('enterpriseId' in value) || value['enterpriseId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LogInEnterpriseEmployeeRequestFromJSON(json: any): LogInEnterpriseEmployeeRequest {
    return LogInEnterpriseEmployeeRequestFromJSONTyped(json, false);
}

export function LogInEnterpriseEmployeeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInEnterpriseEmployeeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enterpriseId': json['enterpriseId'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function LogInEnterpriseEmployeeRequestToJSON(json: any): LogInEnterpriseEmployeeRequest {
    return LogInEnterpriseEmployeeRequestToJSONTyped(json, false);
}

export function LogInEnterpriseEmployeeRequestToJSONTyped(value?: LogInEnterpriseEmployeeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enterpriseId': value['enterpriseId'],
        'username': value['username'],
        'password': value['password'],
    };
}

