/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchRegularAdminRequest
 */
export interface PatchRegularAdminRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchRegularAdminRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchRegularAdminRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchRegularAdminRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchRegularAdminRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the PatchRegularAdminRequest interface.
 */
export function instanceOfPatchRegularAdminRequest(value: object): value is PatchRegularAdminRequest {
    return true;
}

export function PatchRegularAdminRequestFromJSON(json: any): PatchRegularAdminRequest {
    return PatchRegularAdminRequestFromJSONTyped(json, false);
}

export function PatchRegularAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchRegularAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PatchRegularAdminRequestToJSON(json: any): PatchRegularAdminRequest {
    return PatchRegularAdminRequestToJSONTyped(json, false);
}

export function PatchRegularAdminRequestToJSONTyped(value?: PatchRegularAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'password': value['password'],
    };
}

