/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Slot } from './Slot';
import {
    SlotFromJSON,
    SlotFromJSONTyped,
    SlotToJSON,
    SlotToJSONTyped,
} from './Slot';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface PatchNonCustomEnterpriseServiceRequest
 */
export interface PatchNonCustomEnterpriseServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    description?: string;
    /**
     * 
     * @type {Location}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    location?: Location;
    /**
     * 
     * @type {string}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    timeZone?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    cathegory?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    price?: number;
    /**
     * currency ISO code
     * @type {string}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    currency?: string;
    /**
     * 
     * @type {Array<Slot>}
     * @memberof PatchNonCustomEnterpriseServiceRequest
     */
    slots?: Array<Slot>;
}

/**
 * Check if a given object implements the PatchNonCustomEnterpriseServiceRequest interface.
 */
export function instanceOfPatchNonCustomEnterpriseServiceRequest(value: object): value is PatchNonCustomEnterpriseServiceRequest {
    return true;
}

export function PatchNonCustomEnterpriseServiceRequestFromJSON(json: any): PatchNonCustomEnterpriseServiceRequest {
    return PatchNonCustomEnterpriseServiceRequestFromJSONTyped(json, false);
}

export function PatchNonCustomEnterpriseServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchNonCustomEnterpriseServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
        'cathegory': json['cathegory'] == null ? undefined : json['cathegory'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'slots': json['slots'] == null ? undefined : ((json['slots'] as Array<any>).map(SlotFromJSON)),
    };
}

export function PatchNonCustomEnterpriseServiceRequestToJSON(json: any): PatchNonCustomEnterpriseServiceRequest {
    return PatchNonCustomEnterpriseServiceRequestToJSONTyped(json, false);
}

export function PatchNonCustomEnterpriseServiceRequestToJSONTyped(value?: PatchNonCustomEnterpriseServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timeZone': value['timeZone'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currency': value['currency'],
        'slots': value['slots'] == null ? undefined : ((value['slots'] as Array<any>).map(SlotToJSON)),
    };
}

