/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeWindow } from './TimeWindow';
import {
    TimeWindowFromJSON,
    TimeWindowFromJSONTyped,
    TimeWindowToJSON,
    TimeWindowToJSONTyped,
} from './TimeWindow';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface PatchCustomEnterpriseServiceRequest
 */
export interface PatchCustomEnterpriseServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    description?: string;
    /**
     * 
     * @type {Location}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    location?: Location;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    timeZone?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    maxDistanceKm?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    cathegory?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    price?: number;
    /**
     * currency ISO code
     * @type {string}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    currency?: string;
    /**
     * 
     * @type {Array<TimeWindow>}
     * @memberof PatchCustomEnterpriseServiceRequest
     */
    timeWindows?: Array<TimeWindow>;
}

/**
 * Check if a given object implements the PatchCustomEnterpriseServiceRequest interface.
 */
export function instanceOfPatchCustomEnterpriseServiceRequest(value: object): value is PatchCustomEnterpriseServiceRequest {
    return true;
}

export function PatchCustomEnterpriseServiceRequestFromJSON(json: any): PatchCustomEnterpriseServiceRequest {
    return PatchCustomEnterpriseServiceRequestFromJSONTyped(json, false);
}

export function PatchCustomEnterpriseServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchCustomEnterpriseServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
        'maxDistanceKm': json['maxDistanceKm'] == null ? undefined : json['maxDistanceKm'],
        'cathegory': json['cathegory'] == null ? undefined : json['cathegory'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'timeWindows': json['timeWindows'] == null ? undefined : ((json['timeWindows'] as Array<any>).map(TimeWindowFromJSON)),
    };
}

export function PatchCustomEnterpriseServiceRequestToJSON(json: any): PatchCustomEnterpriseServiceRequest {
    return PatchCustomEnterpriseServiceRequestToJSONTyped(json, false);
}

export function PatchCustomEnterpriseServiceRequestToJSONTyped(value?: PatchCustomEnterpriseServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': LocationToJSON(value['location']),
        'timeZone': value['timeZone'],
        'maxDistanceKm': value['maxDistanceKm'],
        'cathegory': value['cathegory'],
        'price': value['price'],
        'currency': value['currency'],
        'timeWindows': value['timeWindows'] == null ? undefined : ((value['timeWindows'] as Array<any>).map(TimeWindowToJSON)),
    };
}

