/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RejectPendingAppointmentRequest
 */
export interface RejectPendingAppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof RejectPendingAppointmentRequest
     */
    rejectionMessage?: string;
}

/**
 * Check if a given object implements the RejectPendingAppointmentRequest interface.
 */
export function instanceOfRejectPendingAppointmentRequest(value: object): value is RejectPendingAppointmentRequest {
    return true;
}

export function RejectPendingAppointmentRequestFromJSON(json: any): RejectPendingAppointmentRequest {
    return RejectPendingAppointmentRequestFromJSONTyped(json, false);
}

export function RejectPendingAppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RejectPendingAppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rejectionMessage': json['rejectionMessage'] == null ? undefined : json['rejectionMessage'],
    };
}

export function RejectPendingAppointmentRequestToJSON(json: any): RejectPendingAppointmentRequest {
    return RejectPendingAppointmentRequestToJSONTyped(json, false);
}

export function RejectPendingAppointmentRequestToJSONTyped(value?: RejectPendingAppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rejectionMessage': value['rejectionMessage'],
    };
}

