/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendAdyenSessionResultRequest
 */
export interface SendAdyenSessionResultRequest {
    /**
     * 
     * @type {string}
     * @memberof SendAdyenSessionResultRequest
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof SendAdyenSessionResultRequest
     */
    sessionResultToken: string;
}

/**
 * Check if a given object implements the SendAdyenSessionResultRequest interface.
 */
export function instanceOfSendAdyenSessionResultRequest(value: object): value is SendAdyenSessionResultRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('sessionResultToken' in value) || value['sessionResultToken'] === undefined) return false;
    return true;
}

export function SendAdyenSessionResultRequestFromJSON(json: any): SendAdyenSessionResultRequest {
    return SendAdyenSessionResultRequestFromJSONTyped(json, false);
}

export function SendAdyenSessionResultRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendAdyenSessionResultRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'sessionResultToken': json['sessionResultToken'],
    };
}

export function SendAdyenSessionResultRequestToJSON(json: any): SendAdyenSessionResultRequest {
    return SendAdyenSessionResultRequestToJSONTyped(json, false);
}

export function SendAdyenSessionResultRequestToJSONTyped(value?: SendAdyenSessionResultRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'sessionResultToken': value['sessionResultToken'],
    };
}

