/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendAdyenSessionResultResponse
 */
export interface SendAdyenSessionResultResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SendAdyenSessionResultResponse
     */
    isTransactionSuccessful: boolean;
}

/**
 * Check if a given object implements the SendAdyenSessionResultResponse interface.
 */
export function instanceOfSendAdyenSessionResultResponse(value: object): value is SendAdyenSessionResultResponse {
    if (!('isTransactionSuccessful' in value) || value['isTransactionSuccessful'] === undefined) return false;
    return true;
}

export function SendAdyenSessionResultResponseFromJSON(json: any): SendAdyenSessionResultResponse {
    return SendAdyenSessionResultResponseFromJSONTyped(json, false);
}

export function SendAdyenSessionResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendAdyenSessionResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isTransactionSuccessful': json['isTransactionSuccessful'],
    };
}

export function SendAdyenSessionResultResponseToJSON(json: any): SendAdyenSessionResultResponse {
    return SendAdyenSessionResultResponseToJSONTyped(json, false);
}

export function SendAdyenSessionResultResponseToJSONTyped(value?: SendAdyenSessionResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isTransactionSuccessful': value['isTransactionSuccessful'],
    };
}

