/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSearchResponseItem
 */
export interface ServiceSearchResponseItem {
    /**
     * 
     * @type {number}
     * @memberof ServiceSearchResponseItem
     */
    serviceId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceSearchResponseItem
     */
    serviceName: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceSearchResponseItem
     */
    enterpriseName: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceSearchResponseItem
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceSearchResponseItem
     */
    price: number;
}

/**
 * Check if a given object implements the ServiceSearchResponseItem interface.
 */
export function instanceOfServiceSearchResponseItem(value: object): value is ServiceSearchResponseItem {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('enterpriseName' in value) || value['enterpriseName'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ServiceSearchResponseItemFromJSON(json: any): ServiceSearchResponseItem {
    return ServiceSearchResponseItemFromJSONTyped(json, false);
}

export function ServiceSearchResponseItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSearchResponseItem {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'],
        'serviceName': json['serviceName'],
        'enterpriseName': json['enterpriseName'],
        'address': json['address'],
        'price': json['price'],
    };
}

export function ServiceSearchResponseItemToJSON(json: any): ServiceSearchResponseItem {
    return ServiceSearchResponseItemToJSONTyped(json, false);
}

export function ServiceSearchResponseItemToJSONTyped(value?: ServiceSearchResponseItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'serviceName': value['serviceName'],
        'enterpriseName': value['enterpriseName'],
        'address': value['address'],
        'price': value['price'],
    };
}

