/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayOfWeek } from './DayOfWeek';
import {
    DayOfWeekFromJSON,
    DayOfWeekFromJSONTyped,
    DayOfWeekToJSON,
    DayOfWeekToJSONTyped,
} from './DayOfWeek';

/**
 * 
 * @export
 * @interface Slot
 */
export interface Slot {
    /**
     * 
     * @type {DayOfWeek}
     * @memberof Slot
     */
    dayOfWeek: DayOfWeek;
    /**
     * 
     * @type {string}
     * @memberof Slot
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Slot
     */
    endTime?: string;
}



/**
 * Check if a given object implements the Slot interface.
 */
export function instanceOfSlot(value: object): value is Slot {
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    return true;
}

export function SlotFromJSON(json: any): Slot {
    return SlotFromJSONTyped(json, false);
}

export function SlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Slot {
    if (json == null) {
        return json;
    }
    return {
        
        'dayOfWeek': DayOfWeekFromJSON(json['dayOfWeek']),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
    };
}

export function SlotToJSON(json: any): Slot {
    return SlotToJSONTyped(json, false);
}

export function SlotToJSONTyped(value?: Slot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dayOfWeek': DayOfWeekToJSON(value['dayOfWeek']),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

