/* tslint:disable */
/* eslint-disable */
/**
 * Engineering Thesis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayOfWeek } from './DayOfWeek';
import {
    DayOfWeekFromJSON,
    DayOfWeekFromJSONTyped,
    DayOfWeekToJSON,
    DayOfWeekToJSONTyped,
} from './DayOfWeek';

/**
 * 
 * @export
 * @interface TimeWindow
 */
export interface TimeWindow {
    /**
     * 
     * @type {DayOfWeek}
     * @memberof TimeWindow
     */
    dayOfWeek: DayOfWeek;
    /**
     * 
     * @type {string}
     * @memberof TimeWindow
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof TimeWindow
     */
    endTime: string;
}



/**
 * Check if a given object implements the TimeWindow interface.
 */
export function instanceOfTimeWindow(value: object): value is TimeWindow {
    if (!('dayOfWeek' in value) || value['dayOfWeek'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    return true;
}

export function TimeWindowFromJSON(json: any): TimeWindow {
    return TimeWindowFromJSONTyped(json, false);
}

export function TimeWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'dayOfWeek': DayOfWeekFromJSON(json['dayOfWeek']),
        'startTime': json['startTime'],
        'endTime': json['endTime'],
    };
}

export function TimeWindowToJSON(json: any): TimeWindow {
    return TimeWindowToJSONTyped(json, false);
}

export function TimeWindowToJSONTyped(value?: TimeWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dayOfWeek': DayOfWeekToJSON(value['dayOfWeek']),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

