CREATE SEQUENCE public.user_id_seq
	INCREMENT BY 1
	MINVALUE 0
	MAXVALUE 9223372036854775807
	START 0
	CACHE 1
	NO CYCLE;

CREATE TABLE public.independent_end_user (
	independent_end_user_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id bigint DEFAULT nextval('user_id_seq'::regclass) NOT NULL,
	first_name text NOT NULL,
	last_name text NOT NULL,
	email text NOT NULL,
	password_hash text NOT NULL,
	CONSTRAINT pk_independent_end_user_independent_end_user_id PRIMARY KEY (independent_end_user_id),
	CONSTRAINT uk_independent_end_user_email UNIQUE (email),
	CONSTRAINT uk_independent_end_user_user_id UNIQUE (user_id)
);

CREATE TABLE public.customer (
	customer_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	independent_end_user_id bigint NOT NULL,
	CONSTRAINT pk_customer_customer_id PRIMARY KEY (customer_id),
	CONSTRAINT uk_customer_independent_end_user_id UNIQUE (independent_end_user_id),
	CONSTRAINT fk_customer_independent_end_user_id FOREIGN KEY (independent_end_user_id) REFERENCES public.independent_end_user(independent_end_user_id) ON DELETE CASCADE
);

CREATE TABLE public.entrepreneur (
	entrepreneur_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	independent_end_user_id bigint NOT NULL,
	CONSTRAINT fk_entrepreneur_entrepreneur_id PRIMARY KEY (entrepreneur_id),
	CONSTRAINT uk_entrepreneur_independent_end_user_id UNIQUE (independent_end_user_id),
	CONSTRAINT fk_entrepreneur_independent_end_user_id FOREIGN KEY (independent_end_user_id) REFERENCES public.independent_end_user(independent_end_user_id) ON DELETE CASCADE
);

CREATE TABLE public.enterprise (
	enterprise_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"location" text NOT NULL,
	entrepreneur_id bigint NOT NULL,
	CONSTRAINT pk_enterprise PRIMARY KEY (enterprise_id),
	CONSTRAINT uk_enterprise_entrepreneur_id UNIQUE (entrepreneur_id),
	CONSTRAINT fk_enterprise_entrepreneur_id FOREIGN KEY (entrepreneur_id) REFERENCES public.entrepreneur(entrepreneur_id) ON DELETE CASCADE
);

CREATE TABLE public.employee (
	employee_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	enterprise_id bigint NOT NULL,
	user_id bigint DEFAULT nextval('user_id_seq'::regclass) NOT NULL,
	first_name text NOT NULL,
	last_name text NOT NULL,
	username text NOT NULL,
	password_hash text NOT NULL,
	CONSTRAINT pk_employee PRIMARY KEY (employee_id),
	CONSTRAINT uk_employee_enterprise_id UNIQUE (enterprise_id),
	CONSTRAINT uk_employee_user_id UNIQUE (user_id),
	CONSTRAINT uk_employee_username UNIQUE (username),
	CONSTRAINT fk_employee_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES public.enterprise(enterprise_id) ON DELETE CASCADE
);